#include "Basics.h"

void IgnoreErr(const char* file, unsigned int line, const char* msg, ...)
{

}

const char* DefaultUnitDisplayName[233] = 
{
    /*  0*/ "Terran Marine",
    /*  1*/ "Terran Ghost", 
    /*  2*/ "Terran Vulture",
    /*  3*/ "Terran Goliath", 
    /*  4*/ "Goliath Turret", 
    /*  5*/ "Terran Siege Tank (Tank Mode)", 
    /*  6*/ "Tank Turret type 1",
    /*  7*/ "Terran SCV", 
    /*  8*/ "Terran Wraith",
    /*  9*/ "Terran Science Vessel",
    /* 10*/ "Gui Montag (Firebat)",
    /* 11*/ "Terran Dropship",
    /* 12*/ "Terran Battlecruiser",
    /* 13*/ "Vulture Spider Mine",
    /* 14*/ "Nuclear Missile",
    /* 15*/ "Terran Civilian",
    /* 16*/ "Sarah Kerrigan (Ghost)",
    /* 17*/ "Alan Schezar (Goliath)",
    /* 18*/ "Alan Schezar Turret",
    /* 19*/ "Jim Raynor (Vulture)",
    /* 20*/ "Jim Raynor (Marine)",
    /* 21*/ "Tom Kazansky (Wraith)",
    /* 22*/ "Magellan (Science Vessel)",
    /* 23*/ "Edmund Duke (Tank Mode)",
    /* 24*/ "Edmund Duke Turret (Tank Mode)",
    /* 25*/ "Edmund Duke (Siege Tank)",
    /* 26*/ "Edmund Duke Turret (Siege Mode)",
    /* 27*/ "Arcturus Mengsk (Battlecruiser)",
    /* 28*/ "Hyperion (Battlecruiser)",
    /* 29*/ "Norad II (Battlecruiser)",
    /* 30*/ "Terran Siege Tank (Siege Mode)",
    /* 31*/ "Tank Turret type 2",
    /* 32*/ "Terran Firebat",
    /* 33*/ "Scanner Sweep",
    /* 34*/ "Terran Medic",
    /* 35*/ "Zerg Larva",
    /* 36*/ "Zerg Egg",
    /* 37*/ "Zerg Zergling",
    /* 38*/ "Zerg Hydralisk",
    /* 39*/ "Zerg Ultralisk",
    /* 40*/ "Zerg Broodling",
    /* 41*/ "Zerg Drone",
    /* 42*/ "Zerg Overlord",
    /* 43*/ "Zerg Mutalisk",
    /* 44*/ "Zerg Guardian",
    /* 45*/ "Zerg Queen",
    /* 46*/ "Zerg Defiler",
    /* 47*/ "Zerg Scourge",
    /* 48*/ "Torrasque (Ultralisk)",
    /* 49*/ "Matriarch (Queen)",
    /* 50*/ "Infested Terran",
    /* 51*/ "Infested Kerrigan (Infested Terran)",
    /* 52*/ "Unclean One (Defiler)",
    /* 53*/ "Hunter Killer (Hydralisk)",
    /* 54*/ "Devouring One (Zergling)",
    /* 55*/ "Kukulza (Mutalisk)",
    /* 56*/ "Kukulza (Guardian)",
    /* 57*/ "Yggdrasill (Overlord)",
    /* 58*/ "Terran Valkyrie",
    /* 59*/ "Mutalisk Cocoon",
    /* 60*/ "Protoss Corsair",
    /* 61*/ "Protoss Dark Templar (Unit)",
    /* 62*/ "Zerg Devourer",
    /* 63*/ "Protoss Dark Archon",
    /* 64*/ "Protoss Probe",
    /* 65*/ "Protoss Zealot",
    /* 66*/ "Protoss Dragoon",
    /* 67*/ "Protoss High Templar",
    /* 68*/ "Protoss Archon",
    /* 69*/ "Protoss Shuttle",
    /* 70*/ "Protoss Scout",
    /* 71*/ "Protoss Arbiter",
    /* 72*/ "Protoss Carrier",
    /* 73*/ "Protoss Interceptor",
    /* 74*/ "Protoss Dark Templar (Hero)",
    /* 75*/ "Zertual (Dark Templar)",
    /* 76*/ "Tassadar/Zeratul (Archon)",
    /* 77*/ "Fenix (Zealot)",
    /* 78*/ "Fenix (Dragoon)",
    /* 79*/ "Tassadar (Templar)",
    /* 80*/ "Mojo (Scout)",
    /* 81*/ "Warbringer (Reaver)",
    /* 82*/ "Gantrithor (Carrier)",
    /* 83*/ "Protoss Reaver",
    /* 84*/ "Protoss Observer",
    /* 85*/ "Protoss Scarab",
    /* 86*/ "Danimoth (Arbiter)",
    /* 87*/ "Aldaris (Templar)",
    /* 88*/ "Artanis (Scout)",
    /* 89*/ "Rhynadon (Badlands)",
    /* 90*/ "Bengalaas (Jungle Critter)",
    /* 91*/ "Unused type 1",
    /* 92*/ "Unused type 2",
    /* 93*/ "Scantid (Desert)",
    /* 94*/ "Kakaru (Twilight)",
    /* 95*/ "Ragnasaur (Ash World)",
    /* 96*/ "Ursadon (Ice World)",
    /* 97*/ "Zerg Lurker Egg",
    /* 98*/ "Raszagal (Dark Templar)",
    /* 99*/ "Samir Duran (Ghost)",
    /*100*/ "Alexei Stukov (Ghost)",
    /*101*/ "Map Revealer",
    /*102*/ "Gerard DuGalle (Ghost)",
    /*103*/ "Zerg Lurker",
    /*104*/ "Infested Duran (Infested Terran)",
    /*105*/ "Disruption Web",
    /*106*/ "Terran Command Center",
    /*107*/ "Terran Comsat Station",
    /*108*/ "Terran Nuclear Silo",
    /*109*/ "Terran Supply Depot",
    /*110*/ "Terran Refinery",
    /*111*/ "Terran Barracks",
    /*112*/ "Terran Academy",
    /*113*/ "Terran Factory",
    /*114*/ "Terran Starport",
    /*115*/ "Terran Control Tower",
    /*116*/ "Terran Science Facility",
    /*117*/ "Terran Covert Ops",
    /*118*/ "Terran Physics Lab",
    /*119*/ "Unused Terran Bldg type 1",
    /*120*/ "Terran Machine Shop",
    /*121*/ "Unused Terran Bldg type 2",
    /*122*/ "Terran Engineering Bay",
    /*123*/ "Terran Armory",
    /*124*/ "Terran Missile Turret",
    /*125*/ "Terran Bunker",
    /*126*/ "Norad II (Crashed Battlecruiser)",
    /*127*/ "Ion Cannon",
    /*128*/ "Uraj Crystal",
    /*129*/ "Khalis Crystal",
    /*130*/ "Infested Command Center",
    /*131*/ "Zerg Hatchery",
    /*132*/ "Zerg Lair",
    /*133*/ "Zerg Hive",
    /*134*/ "Zerg Nydus Canal",
    /*135*/ "Zerg Hydralisk Den",
    /*136*/ "Zerg Defiler Mound",
    /*137*/ "Zerg Greater Spire",
    /*138*/ "Zerg Queen's Nest",
    /*139*/ "Zerg Evolution Chamber",
    /*140*/ "Zerg Ultralisk Cavern",
    /*141*/ "Zerg Spire",
    /*142*/ "Zerg Spawning Pool",
    /*143*/ "Zerg Creep Colony",
    /*144*/ "Zerg Spore Colony",
    /*145*/ "Unused Zerg Bldg",
    /*146*/ "Zerg Sunken Colony",
    /*147*/ "Zerg Overmind (With Shell)",
    /*148*/ "Zerg Overmind",
    /*149*/ "Zerg Extractor",
    /*150*/ "Mature Crysalis",
    /*151*/ "Zerg Cerebrate",
    /*152*/ "Zerg Cerebrate Daggoth",
    /*153*/ "Unused Zerg Bldg 5",
    /*154*/ "Protoss Nexus",
    /*155*/ "Protoss Robotics Facility",
    /*156*/ "Protoss Pylon",
    /*157*/ "Protoss Assimilator",
    /*158*/ "Protoss Unused type 1",
    /*159*/ "Protoss Observatory",
    /*160*/ "Protoss Gateway",
    /*161*/ "Protoss Unused type 2",
    /*162*/ "Protoss Photon Cannon",
    /*163*/ "Protoss Citadel of Adun",
    /*164*/ "Protoss Cybernetics Core",
    /*165*/ "Protoss Templar Archives",
    /*166*/ "Protoss Forge",
    /*167*/ "Protoss Stargate",
    /*168*/ "Stasis Cell/Prison",
    /*169*/ "Protoss Fleet Beacon",
    /*170*/ "Protoss Arbiter Tribunal",
    /*171*/ "Protoss Robotics Support Bay",
    /*172*/ "Protoss Shield Battery",
    /*173*/ "Khaydarin Crystal Formation",
    /*174*/ "Protoss Temple",
    /*175*/ "Xel'Naga Temple",
    /*176*/ "Mineral Field (Type 1)",
    /*177*/ "Mineral Field (Type 2)",
    /*178*/ "Mineral Field (Type 3)",
    /*179*/ "Cave (Unused)",
    /*180*/ "Cave-in (Unused)",
    /*181*/ "Catina (Unused)",
    /*182*/ "Mining Platform",
    /*183*/ "Independent Command Center",
    /*184*/ "Independent Starport",
    /*185*/ "Jump Gate",
    /*186*/ "Ruins",
    /*187*/ "Kyadarin Crystal Formation",
    /*188*/ "Vespene Geyser",
    /*189*/ "Warp Gate",
    /*190*/ "Psi Disrupter",
    /*191*/ "Zerg Marker",
    /*192*/ "Terran Marker",
    /*193*/ "Protoss Marker",
    /*194*/ "Zerg Beacon",
    /*195*/ "Terran Beacon",
    /*196*/ "Protoss Beacon",
    /*197*/ "Zerg Flag Beacon",
    /*198*/ "Terran Flag Beacon",
    /*199*/ "Protoss Flag Beacon",
    /*200*/ "Power Generator",
    /*201*/ "Overmind Cocoon",
    /*202*/ "Dark Swarm",
    /*203*/ "Floor Missile Trap",
    /*204*/ "Floor Hatch (Unused)",
    /*205*/ "Left Upper Level Door",
    /*206*/ "Right Upper Level Door",
    /*207*/ "Left Pit Door",
    /*208*/ "Right Pit Door",
    /*209*/ "Floor Gun Trap",
    /*210*/ "Left Wall Missile Trap",
    /*211*/ "Left Wall Flame Trap",
    /*212*/ "Right Wall Missile Trap",
    /*213*/ "Right Wall Flame Trap",
    /*214*/ "Start Location",
    /*215*/ "Flag",
    /*216*/ "Young Chrysalis",
    /*217*/ "Psi Emitter",
    /*218*/ "Data Disc",
    /*219*/ "Khaydarin Crystal",
    /*220*/ "Mineral Chunk (Type 1)",
    /*221*/ "Mineral Chunk (Type 2)",
    /*222*/ "Vespene Orb (Protoss Type 1)",
    /*223*/ "Vespene Orb (Protoss Type 2)",
    /*224*/ "Vespene Sac (Zerg Type 1)",
    /*225*/ "Vespene Sac (Zerg Type 2)",
    /*226*/ "Vespene Tank (Terran Type 1)",
    /*227*/ "Vespene Tank (Terran Type 2)",
    /*228*/ "ID:228",
    /*229*/ "[any unit]",
    /*230*/ "[men]",
    /*231*/ "[buildings]",
    /*232*/ "[factories]",
};

const char* LegacyTextTrigDisplayName[233] = 
{
    /*  0*/ "Terran Marine",
    /*  1*/ "Terran Ghost", 
    /*  2*/ "Terran Vulture",
    /*  3*/ "Terran Goliath", 
    /*  4*/ "Goliath Turret", 
    /*  5*/ "Terran Siege Tank (Tank Mode)", 
    /*  6*/ "Siege Tank Turret (Tank Mode)",
    /*  7*/ "Terran SCV", 
    /*  8*/ "Terran Wraith",
    /*  9*/ "Terran Science Vessel",
    /* 10*/ "Gui Montag (Firebat)",
    /* 11*/ "Terran Dropship",
    /* 12*/ "Terran Battlecruiser",
    /* 13*/ "Spider Mine",
    /* 14*/ "Nuclear Missile",
    /* 15*/ "Terran Civilian",
    /* 16*/ "Sarah Kerrigan (Ghost)",
    /* 17*/ "Alan Schezar (Goliath)",
    /* 18*/ "Alan Turret",
    /* 19*/ "Jim Raynor (Vulture)",
    /* 20*/ "Jim Raynor (Marine)",
    /* 21*/ "Tom Kazansky (Wraith)",
    /* 22*/ "Magellan (Science Vessel)",
    /* 23*/ "Edmund Duke (Siege Tank)",
    /* 24*/ "Duke Turret type 1",
    /* 25*/ "Edmund Duke (Siege Mode)",
    /* 26*/ "Duke Turret type 2",
    /* 27*/ "Arcturus Mengsk (Battlecruiser)",
    /* 28*/ "Hyperion (Battlecruiser)",
    /* 29*/ "Norad II (Battlecruiser)",
    /* 30*/ "Terran Siege Tank (Siege Mode)",
    /* 31*/ "Siege Tank Turret (Siege Mode)",
    /* 32*/ "Terran Firebat",
    /* 33*/ "Scanner Sweep",
    /* 34*/ "Terran Medic",
    /* 35*/ "Zerg Larva",
    /* 36*/ "Zerg Egg",
    /* 37*/ "Zerg Zergling",
    /* 38*/ "Zerg Hydralisk",
    /* 39*/ "Zerg Ultralisk",
    /* 40*/ "Zerg Broodling",
    /* 41*/ "Zerg Drone",
    /* 42*/ "Zerg Overlord",
    /* 43*/ "Zerg Mutalisk",
    /* 44*/ "Zerg Guardian",
    /* 45*/ "Zerg Queen",
    /* 46*/ "Zerg Defiler",
    /* 47*/ "Zerg Scourge",
    /* 48*/ "Torrasque (Ultralisk)",
    /* 49*/ "Matriarch (Queen)",
    /* 50*/ "Infested Terran",
    /* 51*/ "Infested Kerrigan (Infested Terran)",
    /* 52*/ "Unclean One (Defiler)",
    /* 53*/ "Hunter Killer (Hydralisk)",
    /* 54*/ "Devouring One (Zergling)",
    /* 55*/ "Kukulza (Mutalisk)",
    /* 56*/ "Kukulza (Guardian)",
    /* 57*/ "Yggdrasill (Overlord)",
    /* 58*/ "Terran Valkyrie",
    /* 59*/ "Cocoon",
    /* 60*/ "Protoss Corsair",
    /* 61*/ "Protoss Dark Templar",
    /* 62*/ "Zerg Devourer",
    /* 63*/ "Protoss Dark Archon",
    /* 64*/ "Protoss Probe",
    /* 65*/ "Protoss Zealot",
    /* 66*/ "Protoss Dragoon",
    /* 67*/ "Protoss High Templar",
    /* 68*/ "Protoss Archon",
    /* 69*/ "Protoss Shuttle",
    /* 70*/ "Protoss Scout",
    /* 71*/ "Protoss Arbiter",
    /* 72*/ "Protoss Carrier",
    /* 73*/ "Protoss Interceptor",
    /* 74*/ "Dark Templar (Hero)",
    /* 75*/ "Zeratul (Dark Templar)",
    /* 76*/ "Tassadar/Zeratul (Archon)",
    /* 77*/ "Fenix (Zealot)",
    /* 78*/ "Fenix (Dragoon)",
    /* 79*/ "Tassadar (Templar)",
    /* 80*/ "Mojo (Scout)",
    /* 81*/ "Warbringer (Reaver)",
    /* 82*/ "Gantrithor (Carrier)",
    /* 83*/ "Protoss Reaver",
    /* 84*/ "Protoss Observer",
    /* 85*/ "Protoss Scarab",
    /* 86*/ "Danimoth (Arbiter)",
    /* 87*/ "Aldaris (Templar)",
    /* 88*/ "Artanis (Scout)",
    /* 89*/ "Rhynadon (Badlands Critter)",
    /* 90*/ "Bengalaas (Jungle)",
    /* 91*/ "Cargo Ship (Unused)",
    /* 92*/ "Mercenary Gunship (Unused)",
    /* 93*/ "Scantid (Desert Critter)",
    /* 94*/ "Kakaru (Twilight Critter)",
    /* 95*/ "Ragnasaur (Ashworld Critter)",
    /* 96*/ "Ursadon (Ice World Critter)",
    /* 97*/ "Lurker Egg",
    /* 98*/ "Raszagal (Corsair)",
    /* 99*/ "Samir Duran (Ghost)",
    /*100*/ "Alexei Stukov (Ghost)",
    /*101*/ "Map Revealer",
    /*102*/ "Gerard DuGalle (BattleCruiser)",
    /*103*/ "Zerg Lurker",
    /*104*/ "Infested Duran",
    /*105*/ "Disruption Field",
    /*106*/ "Terran Command Center",
    /*107*/ "Terran Comsat Station",
    /*108*/ "Terran Nuclear Silo",
    /*109*/ "Terran Supply Depot",
    /*110*/ "Terran Refinery",
    /*111*/ "Terran Barracks",
    /*112*/ "Terran Academy",
    /*113*/ "Terran Factory",
    /*114*/ "Terran Starport",
    /*115*/ "Terran Control Tower",
    /*116*/ "Terran Science Facility",
    /*117*/ "Terran Covert Ops",
    /*118*/ "Terran Physics Lab",
    /*119*/ "Starbase (Unused)",
    /*120*/ "Terran Machine Shop",
    /*121*/ "Repair Bay (Unused)",
    /*122*/ "Terran Engineering Bay",
    /*123*/ "Terran Armory",
    /*124*/ "Terran Missile Turret",
    /*125*/ "Terran Bunker",
    /*126*/ "Norad II (Crashed)",
    /*127*/ "Ion Cannon",
    /*128*/ "Uraj Crystal",
    /*129*/ "Khalis Crystal",
    /*130*/ "Infested Command Center",
    /*131*/ "Zerg Hatchery",
    /*132*/ "Zerg Lair",
    /*133*/ "Zerg Hive",
    /*134*/ "Zerg Nydus Canal",
    /*135*/ "Zerg Hydralisk Den",
    /*136*/ "Zerg Defiler Mound",
    /*137*/ "Zerg Greater Spire",
    /*138*/ "Zerg Queen's Nest",
    /*139*/ "Zerg Evolution Chamber",
    /*140*/ "Zerg Ultralisk Cavern",
    /*141*/ "Zerg Spire",
    /*142*/ "Zerg Spawning Pool",
    /*143*/ "Zerg Creep Colony",
    /*144*/ "Zerg Spore Colony",
    /*145*/ "Unused Zerg Building 1",
    /*146*/ "Zerg Sunken Colony",
    /*147*/ "Zerg Overmind (With Shell)",
    /*148*/ "Zerg Overmind",
    /*149*/ "Zerg Extractor",
    /*150*/ "Mature Crysalis",
    /*151*/ "Zerg Cerebrate",
    /*152*/ "Zerg Cerebrate Daggoth",
    /*153*/ "Unused Zerg Building 2",
    /*154*/ "Protoss Nexus",
    /*155*/ "Protoss Robotics Facility",
    /*156*/ "Protoss Pylon",
    /*157*/ "Protoss Assimilator",
    /*158*/ "Unused Protoss Building 1",
    /*159*/ "Protoss Observatory",
    /*160*/ "Protoss Gateway",
    /*161*/ "Unused Protoss Building 2",
    /*162*/ "Protoss Photon Cannon",
    /*163*/ "Protoss Citadel of Adun",
    /*164*/ "Protoss Cybernetics Core",
    /*165*/ "Protoss Templar Archives",
    /*166*/ "Protoss Forge",
    /*167*/ "Protoss Stargate",
    /*168*/ "Stasis Cell/Prison",
    /*169*/ "Protoss Fleet Beacon",
    /*170*/ "Protoss Arbiter Tribunal",
    /*171*/ "Protoss Robotics Support Bay",
    /*172*/ "Protoss Shield Battery",
    /*173*/ "Khaydarin Crystal Formation",
    /*174*/ "Protoss Temple",
    /*175*/ "Xel'Naga Temple",
    /*176*/ "Mineral Field (Type 1)",
    /*177*/ "Mineral Field (Type 2)",
    /*178*/ "Mineral Field (Type 3)",
    /*179*/ "Cave",
    /*180*/ "Cave-in",
    /*181*/ "Cantina",
    /*182*/ "Mining Platform (Unused)",
    /*183*/ "Independent Command Center (Unused)",
    /*184*/ "Independent Starport (Unused)",
    /*185*/ "Independent Jump Gate (Unused)",
    /*186*/ "Ruins (Unused)",
    /*187*/ "Khadarin Crystal Formation (Unused)",
    /*188*/ "Vespene Geyser",
    /*189*/ "Warp Gate",
    /*190*/ "Psi Disrupter",
    /*191*/ "Zerg Marker",
    /*192*/ "Terran Marker",
    /*193*/ "Protoss Marker",
    /*194*/ "Zerg Beacon",
    /*195*/ "Terran Beacon",
    /*196*/ "Protoss Beacon",
    /*197*/ "Zerg Flag Beacon",
    /*198*/ "Terran Flag Beacon",
    /*199*/ "Protoss Flag Beacon",
    /*200*/ "Power Generator",
    /*201*/ "Overmind Cocoon",
    /*202*/ "Dark Swarm",
    /*203*/ "Floor Missile Trap",
    /*204*/ "Floor Hatch (Unused)",
    /*205*/ "Left Upper Level Door",
    /*206*/ "Right Upper Level Door",
    /*207*/ "Left Pit Door",
    /*208*/ "Right Pit Door",
    /*209*/ "Floor Gun Trap",
    /*210*/ "Left Wall Missile Trap",
    /*211*/ "Left Wall Flame Trap",
    /*212*/ "Right Wall Missile Trap",
    /*213*/ "Right Wall Flame Trap",
    /*214*/ "Start Location",
    /*215*/ "Flag",
    /*216*/ "Young Chrysalis",
    /*217*/ "Psi Emitter",
    /*218*/ "Data Disc",
    /*219*/ "Khaydarin Crystal",
    /*220*/ "Mineral Cluster Type 1",
    /*221*/ "Mineral Cluster Type 2",
    /*222*/ "Protoss Vespene Gas Orb Type 1",
    /*223*/ "Protoss Vespene Gas Orb Type 2",
    /*224*/ "Zerg Vespene Gas Sac Type 1",
    /*225*/ "Zerg Vespene Gas Sac Type 2",
    /*226*/ "Terran Vespene Gas Tank Type 1",
    /*227*/ "Terran Vespene Gas Tank Type 2",
    /*228*/ "ID:228",
    /*229*/ "Any unit",
    /*230*/ "Men",
    /*231*/ "Buildings",
    /*232*/ "Factories",
};

const char* VirtualSoundFiles[1143] =
{
    "sound\\Zerg\\Drone\\ZDrErr00.WAV",
    "sound\\Misc\\Buzz.wav (1)",
    "sound\\Misc\\PError.WAV",
    "sound\\Misc\\ZBldgPlc.wav (1)",
    "sound\\Misc\\TBldgPlc.wav",
    "sound\\Misc\\PBldgPlc.wav",
    "sound\\Misc\\ExploLrg.wav",
    "sound\\Misc\\ExploMed.wav",
    "sound\\Misc\\ExploSm.wav",
    "sound\\Misc\\Explo1.wav",
    "sound\\Misc\\Explo2.wav",
    "sound\\Misc\\Explo3.wav",
    "sound\\Misc\\Explo4.wav",
    "sound\\Misc\\Explo5.wav",
    "sound\\Misc\\Button.wav",
    "sound\\Misc\\BurrowDn.wav",
    "sound\\Misc\\BurrowUp.wav",
    "sound\\Misc\\OnFirSml.wav",
    "sound\\Misc\\IntoNydus.wav",
    "sound\\Misc\\OutOfGas.wav",
    "sound\\Misc\\youwin.wav",
    "sound\\Misc\\youlose.wav",
    "sound\\Misc\\Transmission.wav",
    "sound\\Misc\\Door\\Door1Opn.wav",
    "sound\\Misc\\Door\\Door1Cls.wav",
    "sound\\Misc\\Door\\Door2Opn.wav",
    "sound\\Misc\\Door\\Door2Cls.wav",
    "sound\\Misc\\Door\\Door3Opn.wav",
    "sound\\Misc\\Door\\Door3Cls.wav",
    "sound\\Misc\\Door\\Door4Opn.wav",
    "sound\\Misc\\Door\\Door4Cls.wav",
    "sound\\Misc\\ZRescue.wav",
    "sound\\Misc\\TRescue.wav",
    "sound\\Misc\\PRescue.wav",
    "sound\\terran\\SCV\\EDrRep00.wav",
    "sound\\terran\\SCV\\EDrRep01.wav",
    "sound\\terran\\SCV\\EDrRep02.wav",
    "sound\\terran\\SCV\\EDrRep03.wav",
    "sound\\terran\\SCV\\EDrRep04.wav",
    "sound\\Misc\\ZOvTra00.wav",
    "sound\\Misc\\TDrTra00.wav",
    "sound\\Misc\\PShTra00.wav",
    "sound\\Misc\\ZOvTra01.wav",
    "sound\\Misc\\TDrTra01.wav",
    "sound\\Misc\\PShTra01.wav",
    "sound\\Misc\\CRITTERS\\JCrWht00.wav",
    "sound\\Misc\\CRITTERS\\JCrWht01.wav",
    "sound\\Misc\\CRITTERS\\JCrWht02.wav",
    "sound\\Misc\\CRITTERS\\JCrDth00.wav",
    "sound\\Misc\\CRITTERS\\LCrWht00.wav",
    "sound\\Misc\\CRITTERS\\LCrWht01.wav",
    "sound\\Misc\\CRITTERS\\LCrWht02.wav",
    "sound\\Misc\\CRITTERS\\LCrDth00.wav",
    "sound\\Misc\\CRITTERS\\BCrWht00.wav",
    "sound\\Misc\\CRITTERS\\BCrWht01.wav",
    "sound\\Misc\\CRITTERS\\BCrWht02.wav",
    "sound\\Misc\\CRITTERS\\BCrDth00.wav",
    "sound\\Bullet\\PArFir00.wav",
    "sound\\Bullet\\ZHyFir00.wav",
    "sound\\Bullet\\ZHyHit00.wav",
    "sound\\Bullet\\ZDrHit00.wav",
    "sound\\Bullet\\LaserHit.wav",
    "sound\\Bullet\\pshield.wav",
    "sound\\Bullet\\SpoogHit.wav",
    "sound\\Bullet\\BlastCan.wav",
    "sound\\Bullet\\BlastGn2.wav",
    "sound\\Bullet\\ZBGHit00.wav",
    "sound\\Bullet\\TTaFir00.wav",
    "sound\\Bullet\\TMaFir00.wav",
    "sound\\Bullet\\TGoFir00.wav",
    "sound\\Bullet\\ZGuFir00.wav",
    "sound\\Bullet\\ZGuHit00.wav",
    "sound\\Bullet\\LASERB.wav",
    "sound\\Bullet\\TPhFi100.wav",
    "sound\\Bullet\\LASRHIT1.wav",
    "sound\\Bullet\\LASRHIT2.wav",
    "sound\\Bullet\\LASRHIT3.wav",
    "sound\\Bullet\\ZLuFir00.wav",
    "sound\\Bullet\\ZLuHit00.wav",
    "sound\\Bullet\\HKMISSLE.wav",
    "sound\\Bullet\\TGoFi200.wav",
    "sound\\Bullet\\TPhFi200.wav",
    "sound\\Bullet\\TNsFir00.wav (1)",
    "sound\\Bullet\\TNsFir00.wav (2)",
    "sound\\Bullet\\TNsHit00.wav",
    "sound\\Bullet\\PhoAtt00.wav",
    "sound\\Bullet\\PhoHit00.wav",
    "sound\\Bullet\\PSIBLADE.wav",
    "sound\\Bullet\\PSIBOLT.wav",
    "sound\\Bullet\\ZQuFir00.wav",
    "sound\\Bullet\\ZQuHit00.wav",
    "sound\\Bullet\\ZQuHit01.wav",
    "sound\\Bullet\\ZQuHit02.wav",
    "sound\\Bullet\\tscFir00.wav",
    "sound\\Bullet\\SHOCKBMB.wav",
    "sound\\Bullet\\TTaFi200.wav",
    "sound\\Bullet\\SHCKLNCH.wav",
    "sound\\Bullet\\TGhFir00.wav",
    "sound\\Bullet\\DragBull.wav",
    "sound\\Bullet\\psaHit00.wav",
    "sound\\Bullet\\LaserB.wav",
    "sound\\Bullet\\pTrFir00.wav",
    "sound\\Bullet\\pTrFir01.wav",
    "sound\\Bullet\\pzeFir00.wav",
    "sound\\Bullet\\tbaFir00.wav",
    "sound\\Bullet\\tvuFir00.wav",
    "sound\\Bullet\\tvuHit00.wav",
    "sound\\Bullet\\tvuHit01.wav",
    "sound\\Bullet\\tvuHit02.wav",
    "sound\\Bullet\\zdeAtt00.wav",
    "sound\\Bullet\\UZeFir00.wav",
    "sound\\Bullet\\UKiFir00.wav",
    "sound\\Bullet\\zmuFir00.wav",
    "sound\\Misc\\ZPwrDown.wav",
    "sound\\Misc\\TPwrDown.wav",
    "sound\\Misc\\PPwrDown.wav",
    "sound\\Zerg\\Advisor\\ZAdUpd00.WAV",
    "sound\\Terran\\Advisor\\TAdUpd00.WAV",
    "sound\\Protoss\\Advisor\\PAdUpd00.WAV",
    "sound\\Zerg\\Advisor\\ZAdUpd01.WAV",
    "sound\\Terran\\Advisor\\TAdUpd01.WAV",
    "sound\\Protoss\\Advisor\\PAdUpd01.WAV",
    "sound\\Zerg\\Advisor\\ZAdUpd02.WAV",
    "sound\\Terran\\Advisor\\TAdUpd02.WAV (1)",
    "sound\\Protoss\\Advisor\\PAdUpd02.WAV",
    "sound\\Terran\\Advisor\\TAdUpd03.WAV",
    "sound\\Zerg\\Advisor\\ZAdUpd04.WAV",
    "sound\\Terran\\Advisor\\TAdUpd04.WAV",
    "sound\\Protoss\\Advisor\\PAdUpd04.WAV",
    "sound\\Terran\\Advisor\\TAdUpd05.WAV",
    "sound\\Terran\\Advisor\\TAdUpd06.WAV",
    "sound\\Terran\\Advisor\\TAdUpd02.WAV (2)",
    "sound\\Protoss\\Advisor\\PAdUpd06.WAV",
    "sound\\Terran\\Advisor\\TAdUpd07.WAV",
    "sound\\Zerg\\Bldg\\ZChRdy00.WAV",
    "sound\\Terran\\SCV\\TSCUpd00.WAV",
    "sound\\Zerg\\DRONE\\ZDrErr00.WAV (1)",
    "sound\\Zerg\\DRONE\\ZDrErr00.WAV (2)",
    "sound\\Misc\\Buzz.wav (2)",
    "sound\\Misc\\PError.wav",
    "sound\\Misc\\ZBldgPlc.wav (2)",
    "sound\\Terran\\Advisor\\tAdErr04.WAV [1]",
    "sound\\Terran\\Advisor\\tAdErr03.WAV (1)",
    "sound\\Terran\\Advisor\\tAdErr03.WAV (2)",
    "sound\\Terran\\Advisor\\tAdErr04.WAV [2]",
    "sound\\Zerg\\Advisor\\ZAdErr00.WAV (1)",
    "sound\\Zerg\\Advisor\\ZAdErr00.WAV (2)",
    "sound\\Terran\\Advisor\\tAdErr00.WAV",
    "sound\\Protoss\\Advisor\\PAdErr00.WAV",
    "sound\\Zerg\\Advisor\\ZAdErr01.WAV",
    "sound\\Terran\\Advisor\\tAdErr01.WAV",
    "sound\\Protoss\\Advisor\\PAdErr01.WAV",
    "sound\\Zerg\\Advisor\\ZAdErr02.WAV",
    "sound\\Terran\\Advisor\\tAdErr02.WAV",
    "sound\\Protoss\\Advisor\\PAdErr02.WAV",
    "sound\\Zerg\\Advisor\\ZAdErr06.WAV",
    "sound\\Terran\\Advisor\\tAdErr06.WAV",
    "sound\\Protoss\\Advisor\\PAdErr06.WAV",
    "sound\\Terran\\SCV\\TSCErr01.WAV",
    "sound\\Terran\\Advisor\\tAdErr04.WAV [3]",
    "sound\\Protoss\\PROBE\\PPrErr00.WAV",
    "sound\\Terran\\SCV\\TSCErr00.WAV",
    "sound\\Terran\\Advisor\\tAdErr04.WAV [4]",
    "sound\\Protoss\\PROBE\\PPrErr01.WAV",
    "sound\\glue\\mousedown2.wav",
    "sound\\glue\\mouseover.wav",
    "sound\\glue\\bnetclick.wav",
    "sound\\glue\\scorefill.wav",
    "sound\\glue\\scorefillend.wav",
    "sound\\glue\\countdown.wav",
    "sound\\glue\\swishlock.wav",
    "sound\\glue\\swishin.wav",
    "sound\\glue\\swishout.wav",
    "sound\\Terran\\SCV\\TSCMin00.wav",
    "sound\\Terran\\SCV\\TSCMin01.wav",
    "sound\\Terran\\BATTLE\\tbardy00.wav",
    "sound\\Terran\\BATTLE\\tbaDth00.wav",
    "sound\\Terran\\BATTLE\\tBaYam01.wav",
    "sound\\Terran\\BATTLE\\tBaYam02.wav",
    "sound\\Terran\\BATTLE\\tbapss00.wav",
    "sound\\Terran\\BATTLE\\tbapss01.wav",
    "sound\\Terran\\BATTLE\\tbapss02.wav",
    "sound\\Terran\\BATTLE\\tbapss03.wav",
    "sound\\Terran\\BATTLE\\tbapss04.wav",
    "sound\\Terran\\BATTLE\\tbawht00.wav",
    "sound\\Terran\\BATTLE\\tbawht01.wav",
    "sound\\Terran\\BATTLE\\tbawht02.wav",
    "sound\\Terran\\BATTLE\\tbawht03.wav",
    "sound\\Terran\\BATTLE\\tbayes00.wav",
    "sound\\Terran\\BATTLE\\tbayes01.wav",
    "sound\\Terran\\BATTLE\\tbayes02.wav",
    "sound\\Terran\\BATTLE\\tbayes03.wav",
    "sound\\Terran\\CIVILIAN\\TCvPss00.WAV",
    "sound\\Terran\\CIVILIAN\\TCvPss01.WAV",
    "sound\\Terran\\CIVILIAN\\TCvPss02.WAV",
    "sound\\Terran\\CIVILIAN\\TCvPss03.WAV",
    "sound\\Terran\\CIVILIAN\\TCvPss04.WAV",
    "sound\\Terran\\CIVILIAN\\TCvWht00.WAV",
    "sound\\Terran\\CIVILIAN\\TCvWht01.WAV",
    "sound\\Terran\\CIVILIAN\\TCvWht02.WAV",
    "sound\\Terran\\CIVILIAN\\TCvWht03.WAV",
    "sound\\Terran\\CIVILIAN\\TCvYes00.WAV",
    "sound\\Terran\\CIVILIAN\\TCvYes01.WAV",
    "sound\\Terran\\CIVILIAN\\TCvYes02.WAV",
    "sound\\Terran\\CIVILIAN\\TCvYes03.WAV",
    "sound\\Terran\\CIVILIAN\\TCvYes04.WAV",
    "sound\\Terran\\CIVILIAN\\TCvDth00.WAV",
    "sound\\Terran\\CIVILIAN\\TCvRdy00.WAV",
    "sound\\Terran\\DROPSHIP\\TDrRdy00.wav",
    "sound\\Terran\\DROPSHIP\\TDrDth00.wav",
    "sound\\Terran\\DROPSHIP\\TDrPss00.wav",
    "sound\\Terran\\DROPSHIP\\TDrPss01.wav",
    "sound\\Terran\\DROPSHIP\\TDrPss02.wav",
    "sound\\Terran\\DROPSHIP\\TDrPss03.wav",
    "sound\\Terran\\DROPSHIP\\TDrWht00.wav",
    "sound\\Terran\\DROPSHIP\\TDrWht01.wav",
    "sound\\Terran\\DROPSHIP\\TDrWht02.wav",
    "sound\\Terran\\DROPSHIP\\TDrWht03.wav",
    "sound\\Terran\\DROPSHIP\\TDrYes00.wav",
    "sound\\Terran\\DROPSHIP\\TDrYes01.wav",
    "sound\\Terran\\DROPSHIP\\TDrYes02.wav",
    "sound\\Terran\\DROPSHIP\\TDrYes03.wav",
    "sound\\Terran\\DROPSHIP\\TDrYes04.wav",
    "sound\\Terran\\DROPSHIP\\TDrYes05.wav",
    "sound\\Terran\\GHOST\\TGhRdy00.wav",
    "sound\\Terran\\GHOST\\TGhPss00.wav",
    "sound\\Terran\\GHOST\\TGhPss01.wav",
    "sound\\Terran\\GHOST\\TGhPss02.wav",
    "sound\\Terran\\GHOST\\TGhPss03.wav",
    "sound\\Terran\\GHOST\\TGhWht00.wav",
    "sound\\Terran\\GHOST\\TGhWht01.wav",
    "sound\\Terran\\GHOST\\TGhWht02.wav",
    "sound\\Terran\\GHOST\\TGhWht03.wav",
    "sound\\Terran\\GHOST\\TGhYes00.wav",
    "sound\\Terran\\GHOST\\TGhYes01.wav",
    "sound\\Terran\\GHOST\\TGhYes02.wav",
    "sound\\Terran\\GHOST\\TGhYes03.wav",
    "sound\\Terran\\GHOST\\TGhDth00.wav",
    "sound\\Terran\\GHOST\\TGhLas00.wav",
    "sound\\Terran\\GHOST\\TGhLkd00.wav",
    "sound\\Terran\\GOLIATH\\TGoRdy00.wav",
    "sound\\Terran\\GOLIATH\\TGoPss00.wav",
    "sound\\Terran\\GOLIATH\\TGoPss01.WAV",
    "sound\\Terran\\GOLIATH\\TGoPss02.WAV",
    "sound\\Terran\\GOLIATH\\TGoPss03.WAV",
    "sound\\Terran\\GOLIATH\\TGoPss04.WAV",
    "sound\\Terran\\GOLIATH\\TGoPss05.WAV",
    "sound\\Terran\\GOLIATH\\TGoWht00.WAV",
    "sound\\Terran\\GOLIATH\\TGoWht01.WAV",
    "sound\\Terran\\GOLIATH\\TGoWht02.WAV",
    "sound\\Terran\\GOLIATH\\TGoWht03.WAV",
    "sound\\Terran\\GOLIATH\\TGoYes00.WAV",
    "sound\\Terran\\GOLIATH\\TGoYes01.WAV",
    "sound\\Terran\\GOLIATH\\TGoYes02.WAV",
    "sound\\Terran\\GOLIATH\\TGoYes03.WAV",
    "sound\\Terran\\PHOENIX\\TPhRdy00.WAV",
    "sound\\Terran\\PHOENIX\\TPhDth00.WAV",
    "sound\\Terran\\PHOENIX\\TPhPss00.WAV",
    "sound\\Terran\\PHOENIX\\TPhPss01.WAV",
    "sound\\Terran\\PHOENIX\\TPhPss02.WAV",
    "sound\\Terran\\PHOENIX\\TPhPss03.WAV",
    "sound\\Terran\\PHOENIX\\TPhPss04.WAV",
    "sound\\Terran\\PHOENIX\\TPhPss05.WAV",
    "sound\\Terran\\PHOENIX\\TPhPss06.WAV",
    "sound\\Terran\\PHOENIX\\TPhWht00.WAV",
    "sound\\Terran\\PHOENIX\\TPhWht01.WAV",
    "sound\\Terran\\PHOENIX\\TPhWht02.WAV",
    "sound\\Terran\\PHOENIX\\TPhWht03.WAV",
    "sound\\Terran\\PHOENIX\\TPhYes00.WAV",
    "sound\\Terran\\PHOENIX\\TPhYes01.WAV",
    "sound\\Terran\\PHOENIX\\TPhYes02.WAV",
    "sound\\Terran\\PHOENIX\\TPhYes03.WAV",
    "sound\\Terran\\PHOENIX\\TPhClo00.WAV",
    "sound\\Terran\\PHOENIX\\TPhClo01.WAV",
    "sound\\Terran\\MARINE\\TMaRdy00.WAV",
    "sound\\Terran\\MARINE\\TMaDth00.WAV",
    "sound\\Terran\\MARINE\\TMaDth01.WAV",
    "sound\\Terran\\MARINE\\TMaSti00.WAV",
    "sound\\Terran\\MARINE\\TMaSti01.WAV",
    "sound\\Terran\\MARINE\\TMaPss00.WAV",
    "sound\\Terran\\MARINE\\TMaPss01.WAV",
    "sound\\Terran\\MARINE\\TMaPss02.WAV",
    "sound\\Terran\\MARINE\\TMaPss03.WAV",
    "sound\\Terran\\MARINE\\TMaPss04.WAV",
    "sound\\Terran\\MARINE\\TMaPss05.WAV",
    "sound\\Terran\\MARINE\\TMaPss06.WAV",
    "sound\\Terran\\MARINE\\TMaWht00.WAV",
    "sound\\Terran\\MARINE\\TMaWht01.WAV",
    "sound\\Terran\\MARINE\\TMaWht02.WAV",
    "sound\\Terran\\MARINE\\TMaWht03.WAV",
    "sound\\Terran\\MARINE\\TMaYes00.WAV",
    "sound\\Terran\\MARINE\\TMaYes01.WAV",
    "sound\\Terran\\MARINE\\TMaYes02.WAV",
    "sound\\Terran\\MARINE\\TMaYes03.WAV",
    "sound\\Terran\\Firebat\\TFBRdy00.WAV",
    "sound\\Terran\\Firebat\\TFBDth00.WAV",
    "sound\\Terran\\Firebat\\TFBDth01.WAV",
    "sound\\Terran\\Firebat\\TFBDth02.WAV",
    "sound\\Terran\\Firebat\\TFBWht00.WAV",
    "sound\\Terran\\Firebat\\TFBWht01.WAV",
    "sound\\Terran\\Firebat\\TFBWht02.WAV",
    "sound\\Terran\\Firebat\\TFBWht03.WAV",
    "sound\\Terran\\Firebat\\TFBPss00.WAV",
    "sound\\Terran\\Firebat\\TFBPss01.WAV",
    "sound\\Terran\\Firebat\\TFBPss02.WAV",
    "sound\\Terran\\Firebat\\TFBPss03.WAV",
    "sound\\Terran\\Firebat\\TFBPss04.WAV",
    "sound\\Terran\\Firebat\\TFBPss05.WAV",
    "sound\\Terran\\Firebat\\TFBPss06.WAV",
    "sound\\Terran\\Firebat\\TFBYes00.WAV",
    "sound\\Terran\\Firebat\\TFBYes01.WAV",
    "sound\\Terran\\Firebat\\TFBYes02.WAV",
    "sound\\Terran\\Firebat\\TFBYes03.WAV",
    "sound\\Terran\\Firebat\\TFBFir00.WAV",
    "sound\\Terran\\Firebat\\TFBFir01.WAV",
    "sound\\Terran\\TANK\\TTaRdy00.WAV",
    "sound\\Terran\\TANK\\TTaDth00.WAV",
    "sound\\Terran\\TANK\\TTaTra00.WAV",
    "sound\\Terran\\TANK\\TTaTra01.WAV",
    "sound\\Terran\\TANK\\TTaPss00.WAV",
    "sound\\Terran\\TANK\\TTaPss01.WAV",
    "sound\\Terran\\TANK\\TTaPss02.WAV",
    "sound\\Terran\\TANK\\TTaPss03.WAV",
    "sound\\Terran\\TANK\\TTaWht00.WAV",
    "sound\\Terran\\TANK\\TTaWht01.WAV",
    "sound\\Terran\\TANK\\TTaWht02.WAV",
    "sound\\Terran\\TANK\\TTaWht03.WAV",
    "sound\\Terran\\TANK\\TTaYes00.WAV",
    "sound\\Terran\\TANK\\TTaYes01.WAV",
    "sound\\Terran\\TANK\\TTaYes02.WAV",
    "sound\\Terran\\TANK\\TTaYes03.WAV",
    "sound\\Terran\\VESSEL\\TVeRdy00.WAV",
    "sound\\Terran\\VESSEL\\TVePss00.WAV",
    "sound\\Terran\\VESSEL\\TVePss01.WAV",
    "sound\\Terran\\VESSEL\\TVePss02.WAV",
    "sound\\Terran\\VESSEL\\TVePss03.WAV",
    "sound\\Terran\\VESSEL\\TVePss04.WAV",
    "sound\\Terran\\VESSEL\\TVePss05.WAV",
    "sound\\Terran\\VESSEL\\TVePss06.WAV",
    "sound\\Terran\\VESSEL\\TVeWht00.WAV",
    "sound\\Terran\\VESSEL\\TVeWht01.WAV",
    "sound\\Terran\\VESSEL\\TVeWht02.WAV",
    "sound\\Terran\\VESSEL\\TVeWht03.WAV",
    "sound\\Terran\\VESSEL\\TVeYes00.WAV",
    "sound\\Terran\\VESSEL\\TVeYes01.WAV",
    "sound\\Terran\\VESSEL\\TVeYes02.WAV",
    "sound\\Terran\\VESSEL\\TVeYes03.WAV",
    "sound\\Terran\\VESSEL\\TVeDth00.WAV",
    "sound\\Terran\\VESSEL\\TVeDef00.WAV",
    "sound\\Terran\\VESSEL\\TVeEmp00.WAV",
    "sound\\Terran\\VESSEL\\TVeIrr00.WAV",
    "sound\\Terran\\VULTURE\\TVuRdy00.WAV",
    "sound\\Terran\\VULTURE\\TVuDth00.WAV",
    "sound\\Terran\\VULTURE\\TVuMin01.WAV",
    "sound\\Terran\\VULTURE\\TVuMin00.WAV",
    "sound\\Terran\\VULTURE\\TVuPss00.WAV",
    "sound\\Terran\\VULTURE\\TVuPss01.WAV",
    "sound\\Terran\\VULTURE\\TVuPss02.WAV",
    "sound\\Terran\\VULTURE\\TVuPss03.WAV",
    "sound\\Terran\\VULTURE\\TVuWht00.WAV",
    "sound\\Terran\\VULTURE\\TVuWht01.WAV",
    "sound\\Terran\\VULTURE\\TVuWht02.WAV",
    "sound\\Terran\\VULTURE\\TVuWht03.WAV",
    "sound\\Terran\\VULTURE\\TVuYes00.WAV",
    "sound\\Terran\\VULTURE\\TVuYes01.WAV",
    "sound\\Terran\\VULTURE\\TVuYes02.WAV",
    "sound\\Terran\\VULTURE\\TVuYes03.WAV",
    "sound\\Terran\\SCV\\TSCRdy00.WAV",
    "sound\\Terran\\SCV\\TSCDth00.WAV",
    "sound\\Terran\\SCV\\TSCPss00.WAV",
    "sound\\Terran\\SCV\\TSCPss01.WAV",
    "sound\\Terran\\SCV\\TSCPss02.WAV",
    "sound\\Terran\\SCV\\TSCPss03.WAV",
    "sound\\Terran\\SCV\\TSCPss04.WAV",
    "sound\\Terran\\SCV\\TSCPss05.WAV",
    "sound\\Terran\\SCV\\TSCPss06.WAV",
    "sound\\Terran\\SCV\\TSCWht00.WAV",
    "sound\\Terran\\SCV\\TSCWht01.WAV",
    "sound\\Terran\\SCV\\TSCWht02.WAV",
    "sound\\Terran\\SCV\\TSCWht03.WAV",
    "sound\\Terran\\SCV\\TSCYes00.WAV",
    "sound\\Terran\\SCV\\TSCYes01.WAV",
    "sound\\Terran\\SCV\\TSCYes02.WAV",
    "sound\\Terran\\SCV\\TSCYes03.WAV",
    "sound\\Terran\\bldg\\tacwht00.WAV",
    "sound\\Terran\\bldg\\tclwht00.WAV",
    "sound\\Terran\\bldg\\tcswht00.WAV",
    "sound\\Terran\\bldg\\tcsSca00.WAV",
    "sound\\Terran\\bldg\\tddwht00.WAV",
    "sound\\Terran\\bldg\\tglwht00.WAV",
    "sound\\Misc\\UICWht00.wav",
    "sound\\Terran\\bldg\\tmswht00.WAV",
    "sound\\Terran\\bldg\\tmtwht00.WAV",
    "sound\\Misc\\UNrWht00.wav",
    "sound\\Terran\\bldg\\tRlWht00.WAV",
    "sound\\Terran\\bldg\\tnswht00.WAV",
    "sound\\Terran\\bldg\\tpgwht00.WAV",
    "sound\\Terran\\bldg\\tplwht00.WAV",
    "sound\\Misc\\button.wav",
    "sound\\Terran\\bldg\\trewht00.WAV",
    "sound\\Terran\\bldg\\trfwht00.WAV",
    "sound\\Terran\\bldg\\twpwht00.WAV",
    "sound\\Terran\\bldg\\OnFirLrg.wav",
    "sound\\Terran\\SCV\\TScTra00.WAV",
    "sound\\Terran\\RAYNORM\\URaDth00.WAV",
    "sound\\Terran\\RAYNORM\\URaDth01.WAV",
    "sound\\Terran\\RAYNORM\\URaPss00.WAV",
    "sound\\Terran\\RAYNORM\\URaPss01.WAV",
    "sound\\Terran\\RAYNORM\\URaPss02.WAV",
    "sound\\Terran\\RAYNORM\\URaPss03.WAV",
    "sound\\Terran\\RAYNORM\\URaWht00.WAV",
    "sound\\Terran\\RAYNORM\\URaWht01.WAV",
    "sound\\Terran\\RAYNORM\\URaWht02.WAV",
    "sound\\Terran\\RAYNORM\\URaWht03.WAV",
    "sound\\Terran\\RAYNORM\\URaYes00.WAV",
    "sound\\Terran\\RAYNORM\\URaYes01.WAV",
    "sound\\Terran\\RAYNORM\\URaYes02.WAV",
    "sound\\Terran\\RAYNORM\\URaYes03.WAV",
    "sound\\Terran\\RAYNORV\\URVPss00.WAV",
    "sound\\Terran\\RAYNORV\\URVPss01.WAV",
    "sound\\Terran\\RAYNORV\\URVPss02.WAV",
    "sound\\Terran\\RAYNORV\\URVPss03.WAV",
    "sound\\Terran\\RAYNORV\\URVWht00.WAV",
    "sound\\Terran\\RAYNORV\\URVWht01.WAV",
    "sound\\Terran\\RAYNORV\\URVWht02.WAV",
    "sound\\Terran\\RAYNORV\\URVWht03.WAV",
    "sound\\Terran\\RAYNORV\\URVYes00.WAV",
    "sound\\Terran\\RAYNORV\\URVYes01.WAV",
    "sound\\Terran\\RAYNORV\\URVYes02.WAV",
    "sound\\Terran\\RAYNORV\\URVYes03.WAV",
    "sound\\Terran\\DUKET\\UDTPss00.WAV",
    "sound\\Terran\\DUKET\\UDTPss01.WAV",
    "sound\\Terran\\DUKET\\UDTPss02.WAV",
    "sound\\Terran\\DUKET\\UDTPss03.WAV",
    "sound\\Terran\\DUKET\\UDTPss04.WAV",
    "sound\\Terran\\DUKET\\UDTWht00.WAV",
    "sound\\Terran\\DUKET\\UDTWht01.WAV",
    "sound\\Terran\\DUKET\\UDTWht02.WAV",
    "sound\\Terran\\DUKET\\UDTWht03.WAV",
    "sound\\Terran\\DUKET\\UDTYes00.WAV",
    "sound\\Terran\\DUKET\\UDTYes01.WAV",
    "sound\\Terran\\DUKET\\UDTYes02.WAV",
    "sound\\Terran\\DUKET\\UDTYes03.WAV",
    "sound\\Terran\\DUKEB\\UDupss00.wav",
    "sound\\Terran\\DUKEB\\UDupss01.wav",
    "sound\\Terran\\DUKEB\\UDupss02.wav",
    "sound\\Terran\\DUKEB\\UDupss03.wav",
    "sound\\Terran\\DUKEB\\UDupss04.wav",
    "sound\\Terran\\DUKEB\\UDuwht00.wav",
    "sound\\Terran\\DUKEB\\UDuwht01.wav",
    "sound\\Terran\\DUKEB\\UDuwht02.wav",
    "sound\\Terran\\DUKEB\\UDuwht03.wav",
    "sound\\Terran\\DUKEB\\UDuyes00.wav",
    "sound\\Terran\\DUKEB\\UDuyes01.wav",
    "sound\\Terran\\DUKEB\\UDuyes02.wav",
    "sound\\Terran\\DUKEB\\UDuyes03.wav",
    "sound\\Terran\\KERRIGAN\\UKePss00.wav",
    "sound\\Terran\\KERRIGAN\\UKePss01.wav",
    "sound\\Terran\\KERRIGAN\\UKePss02.wav",
    "sound\\Terran\\KERRIGAN\\UKePss03.wav",
    "sound\\Terran\\KERRIGAN\\UKePss04.wav",
    "sound\\Terran\\KERRIGAN\\UKeWht00.wav",
    "sound\\Terran\\KERRIGAN\\UKeWht01.wav",
    "sound\\Terran\\KERRIGAN\\UKeWht02.wav",
    "sound\\Terran\\KERRIGAN\\UKeWht03.wav",
    "sound\\Terran\\KERRIGAN\\UKeYes00.wav",
    "sound\\Terran\\KERRIGAN\\UKeYes01.wav",
    "sound\\Terran\\KERRIGAN\\UKeYes02.wav",
    "sound\\Terran\\KERRIGAN\\UKeYes03.wav",
    "sound\\Terran\\KERRIGAN\\UKeDth00.wav",
    "sound\\Misc\\LiftOff.WAV",
    "sound\\Misc\\Land.WAV",
    "sound\\Protoss\\Bldg\\pAcWht00.WAV",
    "sound\\Protoss\\Bldg\\pAsWht00.WAV",
    "sound\\Protoss\\Bldg\\pBaWht00.WAV",
    "sound\\Protoss\\Bldg\\pBeWht00.WAV",
    "sound\\Protoss\\Bldg\\pCiWht00.WAV",
    "sound\\Protoss\\Bldg\\pFoWht00.WAV",
    "sound\\Protoss\\Bldg\\pGaWht00.WAV",
    "sound\\Protoss\\Bldg\\pGcWht00.WAV",
    "sound\\Protoss\\Bldg\\PbaAct00.wav",
    "sound\\Misc\\Button.WAV",
    "sound\\Protoss\\Bldg\\pNaWht00.WAV (1)",
    "sound\\Protoss\\Bldg\\pNeWht00.WAV",
    "sound\\Protoss\\Bldg\\pPBWht00.WAV",
    "sound\\Misc\\UTmWht00.WAV",
    "sound\\Protoss\\Bldg\\pPyWht00.WAV",
    "sound\\Protoss\\Bldg\\pRoWht00.WAV",
    "sound\\Misc\\UPiWht00.WAV",
    "sound\\Protoss\\Bldg\\PTrWht00.WAV",
    "sound\\Protoss\\Bldg\\pWaWht00.WAV",
    "sound\\Protoss\\DRAGOON\\PDrRdy00.WAV",
    "sound\\Protoss\\DRAGOON\\PDrDth00.WAV",
    "sound\\Protoss\\DRAGOON\\PDrPss00.WAV",
    "sound\\Protoss\\DRAGOON\\PDrPss01.WAV",
    "sound\\Protoss\\DRAGOON\\PDrPss02.WAV",
    "sound\\Protoss\\DRAGOON\\PDrPss03.WAV",
    "sound\\Protoss\\DRAGOON\\PDrWht00.WAV",
    "sound\\Protoss\\DRAGOON\\PDrWht01.WAV",
    "sound\\Protoss\\DRAGOON\\PDrWht02.WAV",
    "sound\\Protoss\\DRAGOON\\PDrWht03.WAV",
    "sound\\Protoss\\DRAGOON\\PDrWht04.WAV",
    "sound\\Protoss\\DRAGOON\\PDrWht05.WAV",
    "sound\\Protoss\\DRAGOON\\PDrWht06.WAV",
    "sound\\Protoss\\DRAGOON\\PDrWht07.WAV",
    "sound\\Protoss\\DRAGOON\\PDrYes00.WAV",
    "sound\\Protoss\\DRAGOON\\PDrYes01.WAV",
    "sound\\Protoss\\DRAGOON\\PDrYes02.WAV",
    "sound\\Protoss\\DRAGOON\\PDrYes03.WAV",
    "sound\\Protoss\\DRAGOON\\PDrYes04.WAV",
    "sound\\Protoss\\DRAGOON\\PDrYes05.WAV",
    "sound\\Protoss\\DRAGOON\\PDrYes06.WAV",
    "sound\\Protoss\\SHUTTLE\\PShRdy00.WAV",
    "sound\\Protoss\\SHUTTLE\\PShDth00.WAV",
    "sound\\Protoss\\SHUTTLE\\PShPss00.WAV",
    "sound\\Protoss\\SHUTTLE\\PShPss01.WAV",
    "sound\\Protoss\\SHUTTLE\\PShPss02.WAV",
    "sound\\Protoss\\SHUTTLE\\PShPss03.WAV",
    "sound\\Protoss\\SHUTTLE\\PShPss04.WAV",
    "sound\\Protoss\\SHUTTLE\\PShWht00.WAV",
    "sound\\Protoss\\SHUTTLE\\PShWht01.WAV",
    "sound\\Protoss\\SHUTTLE\\PShWht02.WAV",
    "sound\\Protoss\\SHUTTLE\\PShWht03.WAV",
    "sound\\Protoss\\SHUTTLE\\PShYes00.WAV",
    "sound\\Protoss\\SHUTTLE\\PShYes01.WAV",
    "sound\\Protoss\\SHUTTLE\\PShYes02.WAV",
    "sound\\Protoss\\SHUTTLE\\PShYes03.WAV",
    "sound\\Protoss\\SHUTTLE\\pshBld00.wav",
    "sound\\Protoss\\SHUTTLE\\pshBld03.wav",
    "sound\\Protoss\\SHUTTLE\\pshBld01.wav",
    "sound\\Protoss\\SHUTTLE\\pshBld02.wav",
    "sound\\Protoss\\SHUTTLE\\pshBld04.wav",
    "sound\\Protoss\\Scout\\PScDth00.WAV",
    "sound\\Protoss\\SCOUT\\PScRdy00.WAV",
    "sound\\Protoss\\Scout\\PScPss00.WAV",
    "sound\\Protoss\\Scout\\PScPss01.WAV",
    "sound\\Protoss\\Scout\\PScPss02.WAV",
    "sound\\Protoss\\Scout\\PScPss03.WAV",
    "sound\\Protoss\\Scout\\PScPss04.WAV",
    "sound\\Protoss\\Scout\\PScWht00.WAV",
    "sound\\Protoss\\Scout\\PScWht01.WAV",
    "sound\\Protoss\\Scout\\PScWht02.WAV",
    "sound\\Protoss\\Scout\\PScWht03.WAV",
    "sound\\Protoss\\Scout\\PScYes00.WAV",
    "sound\\Protoss\\Scout\\PScYes01.WAV",
    "sound\\Protoss\\Scout\\PScYes02.WAV",
    "sound\\Protoss\\Scout\\PScYes03.WAV",
    "sound\\Protoss\\ARBITER\\PAbCag00.WAV",
    "sound\\Protoss\\ARBITER\\PAbRdy00.WAV",
    "sound\\Protoss\\ARBITER\\PAbFol00.WAV",
    "sound\\Protoss\\ARBITER\\PAbFol01.WAV",
    "sound\\Protoss\\ARBITER\\PAbFol02.WAV",
    "sound\\Protoss\\ARBITER\\PAbFol03.WAV",
    "sound\\Protoss\\ARBITER\\PAbPss00.WAV",
    "sound\\Protoss\\ARBITER\\PAbPss01.WAV",
    "sound\\Protoss\\ARBITER\\PAbPss02.WAV",
    "sound\\Protoss\\ARBITER\\PAbPss03.WAV",
    "sound\\Protoss\\ARBITER\\PAbPss04.WAV",
    "sound\\Protoss\\ARBITER\\PAbWht00.WAV",
    "sound\\Protoss\\ARBITER\\PAbWht01.WAV",
    "sound\\Protoss\\ARBITER\\PAbWht02.WAV",
    "sound\\Protoss\\ARBITER\\PAbWht03.WAV",
    "sound\\Protoss\\ARBITER\\PAbYes00.WAV",
    "sound\\Protoss\\ARBITER\\PAbYes01.WAV",
    "sound\\Protoss\\ARBITER\\PAbYes02.WAV",
    "sound\\Protoss\\ARBITER\\PAbDth00.WAV",
    "sound\\Protoss\\ARCHON\\PArRdy00.WAV",
    "sound\\Protoss\\ARCHON\\PArMin00.WAV",
    "sound\\Protoss\\ARCHON\\PArPss00.WAV",
    "sound\\Protoss\\ARCHON\\PArPss01.WAV",
    "sound\\Protoss\\ARCHON\\PArPss02.WAV",
    "sound\\Protoss\\ARCHON\\PArPss03.WAV",
    "sound\\Protoss\\ARCHON\\PArWht00.WAV",
    "sound\\Protoss\\ARCHON\\PArWht01.WAV",
    "sound\\Protoss\\ARCHON\\PArWht02.WAV",
    "sound\\Protoss\\ARCHON\\PArWht03.WAV",
    "sound\\Protoss\\ARCHON\\PArYes00.WAV",
    "sound\\Protoss\\ARCHON\\PArYes01.WAV",
    "sound\\Protoss\\ARCHON\\PArYes02.WAV",
    "sound\\Protoss\\ARCHON\\PArYes03.WAV",
    "sound\\Protoss\\ARCHON\\PArDth00.WAV",
    "sound\\Protoss\\CARRIER\\PCaRdy00.WAV",
    "sound\\Protoss\\Carrier\\PCaPss00.WAV",
    "sound\\Protoss\\Carrier\\PCaPss01.WAV",
    "sound\\Protoss\\Carrier\\PCaPss02.WAV",
    "sound\\Protoss\\Carrier\\PCaPss03.WAV",
    "sound\\Protoss\\Carrier\\PCaWht00.WAV",
    "sound\\Protoss\\Carrier\\PCaWht01.WAV",
    "sound\\Protoss\\Carrier\\PCaWht02.WAV",
    "sound\\Protoss\\Carrier\\PCaWht03.WAV",
    "sound\\Protoss\\Carrier\\PCaYes00.WAV",
    "sound\\Protoss\\Carrier\\PCaYes01.WAV",
    "sound\\Protoss\\Carrier\\PCaYes02.WAV",
    "sound\\Protoss\\Carrier\\PCaYes03.WAV",
    "sound\\Protoss\\Carrier\\PCaDth00.WAV",
    "sound\\Protoss\\Carrier\\PCaDth01.WAV",
    "sound\\Protoss\\PROBE\\PPrRdy00.WAV",
    "sound\\Protoss\\PROBE\\PPrDth00.WAV",
    "sound\\Protoss\\PROBE\\PPrAtt00.WAV",
    "sound\\Protoss\\PROBE\\PPrAtt01.WAV",
    "sound\\Protoss\\PROBE\\PPrMin00.WAV",
    "sound\\Protoss\\PROBE\\PPrPss00.WAV (1)",
    "sound\\Protoss\\PROBE\\PPrPss01.WAV",
    "sound\\Protoss\\PROBE\\PPrPss02.WAV",
    "sound\\Protoss\\PROBE\\PPrPss03.WAV",
    "sound\\Protoss\\PROBE\\PPrWht00.WAV",
    "sound\\Protoss\\PROBE\\PPrWht01.WAV",
    "sound\\Protoss\\PROBE\\PPrWht02.WAV",
    "sound\\Protoss\\PROBE\\PPrWht03.WAV",
    "sound\\Protoss\\PROBE\\PPrYes00.WAV",
    "sound\\Protoss\\PROBE\\PPrYes01.WAV",
    "sound\\Protoss\\PROBE\\PPrYes02.WAV",
    "sound\\Protoss\\PROBE\\PPrYes03.WAV",
    "sound\\Protoss\\INTERCEP\\PInLau00.WAV",
    "sound\\Protoss\\PROBE\\PPrPss00.WAV (2)",
    "sound\\Protoss\\TEMPLAR\\PTeSum00.WAV (1)",
    "sound\\Protoss\\TEMPLAR\\PTeSum00.WAV (2)",
    "sound\\Protoss\\TEMPLAR\\PTeHal00.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeHal01.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeSto00.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeSto01.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeRdy00.WAV",
    "sound\\Protoss\\TEMPLAR\\PTePss00.WAV",
    "sound\\Protoss\\TEMPLAR\\PTePss01.WAV",
    "sound\\Protoss\\TEMPLAR\\PTePss02.WAV",
    "sound\\Protoss\\TEMPLAR\\PTePss03.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeWht00.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeWht01.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeWht02.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeWht03.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeYes00.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeYes01.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeYes02.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeYes03.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeDth00.WAV",
    "sound\\Protoss\\TEMPLAR\\PTeMov00.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrRdy00.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrDth00.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrPss00.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrPss01.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrPss02.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrWht00.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrWht01.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrWht02.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrWht03.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrYes00.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrYes01.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrYes02.WAV",
    "sound\\Protoss\\TRILOBYTE\\PTrYes03.WAV",
    "sound\\Protoss\\Witness\\PWiRdy00.WAV",
    "sound\\Protoss\\Witness\\PWiDth00.WAV",
    "sound\\Protoss\\Witness\\PWiDth01.WAV",
    "sound\\Protoss\\Witness\\PWiPss00.WAV",
    "sound\\Protoss\\Witness\\PWiPss01.WAV",
    "sound\\Protoss\\Witness\\PWiPss02.WAV",
    "sound\\Protoss\\Witness\\PWiPss03.WAV",
    "sound\\Protoss\\Witness\\PWiPss04.WAV",
    "sound\\Protoss\\Witness\\PWiWht00.WAV",
    "sound\\Protoss\\Witness\\PWiWht01.WAV",
    "sound\\Protoss\\Witness\\PWiYes00.WAV",
    "sound\\Protoss\\Witness\\PWiYes01.WAV",
    "sound\\Protoss\\ZEALOT\\pzeAtt00.WAV",
    "sound\\Protoss\\ZEALOT\\pzeAtt01.WAV",
    "sound\\Protoss\\ZEALOT\\pzeHit00.WAV",
    "sound\\Protoss\\ZEALOT\\PZeRag00.wav",
    "sound\\Protoss\\ZEALOT\\PZeRdy00.WAV",
    "sound\\Protoss\\ZEALOT\\PZePss00.WAV",
    "sound\\Protoss\\ZEALOT\\PZePss01.WAV",
    "sound\\Protoss\\ZEALOT\\PZePss02.WAV",
    "sound\\Protoss\\ZEALOT\\PZeWht00.WAV",
    "sound\\Protoss\\ZEALOT\\PZeWht01.WAV",
    "sound\\Protoss\\ZEALOT\\PZeWht02.WAV",
    "sound\\Protoss\\ZEALOT\\PZeWht03.WAV",
    "sound\\Protoss\\ZEALOT\\PZeYes00.WAV",
    "sound\\Protoss\\ZEALOT\\PZeYes01.WAV",
    "sound\\Protoss\\ZEALOT\\PZeYes02.WAV",
    "sound\\Protoss\\ZEALOT\\PZeYes03.WAV",
    "sound\\Protoss\\ZEALOT\\PZeDth00.WAV",
    "sound\\Protoss\\FENIXD\\UFdPss00.WAV",
    "sound\\Protoss\\FENIXD\\UFdPss01.WAV",
    "sound\\Protoss\\FENIXD\\UFdPss02.WAV",
    "sound\\Protoss\\FENIXD\\UFdPss03.WAV",
    "sound\\Protoss\\FENIXD\\UFdWht00.WAV",
    "sound\\Protoss\\FENIXD\\UFdWht01.WAV",
    "sound\\Protoss\\FENIXD\\UFdWht02.WAV",
    "sound\\Protoss\\FENIXD\\UFdWht03.WAV",
    "sound\\Protoss\\FENIXD\\UFdYes00.WAV",
    "sound\\Protoss\\FENIXD\\UFdYes01.WAV",
    "sound\\Protoss\\FENIXD\\UFdYes02.WAV",
    "sound\\Protoss\\FENIXD\\UFdYes03.WAV",
    "sound\\Protoss\\FENIXZ\\UFePss00.WAV",
    "sound\\Protoss\\FENIXZ\\UFePss01.WAV",
    "sound\\Protoss\\FENIXZ\\UFePss02.WAV",
    "sound\\Protoss\\FENIXZ\\UFePss03.WAV",
    "sound\\Protoss\\FENIXZ\\UFeWht00.WAV",
    "sound\\Protoss\\FENIXZ\\UFeWht01.WAV",
    "sound\\Protoss\\FENIXZ\\UFeWht02.WAV",
    "sound\\Protoss\\FENIXZ\\UFeWht03.WAV",
    "sound\\Protoss\\FENIXZ\\UFeYes00.WAV",
    "sound\\Protoss\\FENIXZ\\UFeYes01.WAV",
    "sound\\Protoss\\FENIXZ\\UFeYes02.WAV",
    "sound\\Protoss\\FENIXZ\\UFeYes03.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCPss00.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCPss01.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCPss02.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCPss03.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCWht00.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCWht01.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCWht02.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCWht03.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCYes00.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCYes01.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCYes02.WAV",
    "sound\\Protoss\\GANTRITHOR\\UTCYes03.WAV",
    "sound\\Protoss\\TASSADAR\\UTaPss00.WAV",
    "sound\\Protoss\\TASSADAR\\UTaPss01.WAV",
    "sound\\Protoss\\TASSADAR\\UTaPss02.WAV",
    "sound\\Protoss\\TASSADAR\\UTaPss03.WAV",
    "sound\\Protoss\\TASSADAR\\UTaWht00.WAV",
    "sound\\Protoss\\TASSADAR\\UTaWht01.WAV",
    "sound\\Protoss\\TASSADAR\\UTaWht02.WAV",
    "sound\\Protoss\\TASSADAR\\UTaWht03.WAV",
    "sound\\Protoss\\TASSADAR\\UTaYes00.WAV",
    "sound\\Protoss\\TASSADAR\\UTaYes01.WAV",
    "sound\\Protoss\\TASSADAR\\UTaYes02.WAV",
    "sound\\Protoss\\TASSADAR\\UTaYes03.WAV",
    "sound\\Protoss\\TASSADAR\\UTaDth00.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTRdy00.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTPss00.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTPss01.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTPss02.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTPss03.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTWht00.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTWht01.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTWht02.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTWht03.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTYes00.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTYes01.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTYes02.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTYes03.WAV",
    "sound\\Protoss\\DARKTEMPLAR\\PDTDth00.WAV",
    "sound\\Protoss\\ZERATUL\\UZePss00.WAV",
    "sound\\Protoss\\ZERATUL\\UZePss01.WAV",
    "sound\\Protoss\\ZERATUL\\UZePss02.WAV",
    "sound\\Protoss\\ZERATUL\\UZePss03.WAV",
    "sound\\Protoss\\ZERATUL\\UZeWht00.WAV",
    "sound\\Protoss\\ZERATUL\\UZeWht01.WAV",
    "sound\\Protoss\\ZERATUL\\UZeWht02.WAV",
    "sound\\Protoss\\ZERATUL\\UZeWht03.WAV",
    "sound\\Protoss\\ZERATUL\\UZeYes00.WAV",
    "sound\\Protoss\\ZERATUL\\UZeYes01.WAV",
    "sound\\Protoss\\ZERATUL\\UZeYes02.WAV",
    "sound\\Protoss\\ZERATUL\\UZeYes03.WAV",
    "sound\\Protoss\\ZERATUL\\UZeDth00.WAV",
    "sound\\Zerg\\Bldg\\ZChWht00.WAV",
    "sound\\Zerg\\Bldg\\ZCbWht00.WAV",
    "sound\\Zerg\\Bldg\\ZEvWht00.WAV",
    "sound\\Zerg\\Bldg\\ZFcWht00.WAV",
    "sound\\Zerg\\Bldg\\ZHaWht00.WAV",
    "sound\\Zerg\\Bldg\\ZHiWht00.WAV",
    "sound\\Zerg\\Bldg\\ZIgWht00.WAV",
    "sound\\Zerg\\Bldg\\ZLrWht00.WAV",
    "sound\\Zerg\\Bldg\\ZLuWht00.WAV",
    "sound\\Zerg\\Bldg\\ZMcWht00.WAV",
    "sound\\Protoss\\Bldg\\pNaWht00.WAV (2)",
    "sound\\Zerg\\Bldg\\ZMhWht00.WAV",
    "sound\\Zerg\\Bldg\\ZNeWht00.WAV",
    "sound\\Zerg\\Bldg\\ZNyWht00.WAV",
    "sound\\Zerg\\Bldg\\ZO1Wht00.WAV",
    "sound\\Zerg\\Bldg\\ZRcWht00.WAV",
    "sound\\Zerg\\Bldg\\ZSbWht00.WAV",
    "sound\\Zerg\\Bldg\\ZScWht00.WAV",
    "sound\\Zerg\\Bldg\\ZSpWht00.WAV",
    "sound\\Zerg\\Bldg\\ZBldgDth.WAV",
    "sound\\Zerg\\AVENGER\\ZAvRdy00.WAV",
    "sound\\Zerg\\AVENGER\\ZAvDth00.WAV",
    "sound\\Zerg\\AVENGER\\ZAvAtt00.WAV",
    "sound\\Zerg\\AVENGER\\ZAvHit00.WAV",
    "sound\\Zerg\\AVENGER\\ZAvPss00.WAV",
    "sound\\Zerg\\AVENGER\\ZAvPss01.WAV",
    "sound\\Zerg\\AVENGER\\ZAvWht00.WAV",
    "sound\\Zerg\\AVENGER\\ZAvWht01.WAV",
    "sound\\Zerg\\AVENGER\\ZAvYes00.WAV",
    "sound\\Zerg\\AVENGER\\ZAvYes01.WAV",
    "sound\\Zerg\\BROODLING\\ZBrDth00.WAV",
    "sound\\Zerg\\BROODLING\\ZBrAtt00.WAV",
    "sound\\Zerg\\BROODLING\\ZBrRdy00.WAV",
    "sound\\Zerg\\BROODLING\\ZBrPss00.WAV",
    "sound\\Zerg\\BROODLING\\ZBrPss01.WAV",
    "sound\\Zerg\\BROODLING\\ZBrPss02.WAV",
    "sound\\Zerg\\BROODLING\\ZBrPss03.WAV",
    "sound\\Zerg\\BROODLING\\ZBrWht00.WAV",
    "sound\\Zerg\\BROODLING\\ZBrWht01.WAV",
    "sound\\Zerg\\BROODLING\\ZBrWht02.WAV",
    "sound\\Zerg\\BROODLING\\ZBrWht03.WAV",
    "sound\\Zerg\\BROODLING\\ZBrYes00.WAV",
    "sound\\Zerg\\BROODLING\\ZBrYes01.WAV",
    "sound\\Zerg\\BROODLING\\ZBrYes02.WAV",
    "sound\\Zerg\\BUGGUY\\ZBGRdy00.wav (1)",
    "sound\\Zerg\\BUGGUY\\ZBGRdy00.wav (2)",
    "sound\\Zerg\\BUGGUY\\ZBGPss00.wav",
    "sound\\Zerg\\BUGGUY\\ZBGPss01.wav",
    "sound\\Zerg\\BUGGUY\\ZBGPss02.wav",
    "sound\\Zerg\\BUGGUY\\ZBGPss03.wav",
    "sound\\Zerg\\BUGGUY\\ZBGWht00.wav",
    "sound\\Zerg\\BUGGUY\\ZBGWht01.wav",
    "sound\\Zerg\\BUGGUY\\ZBGWht02.wav",
    "sound\\Zerg\\BUGGUY\\ZBGWht03.wav",
    "sound\\Zerg\\BUGGUY\\ZBGYes00.wav",
    "sound\\Zerg\\BUGGUY\\ZBGYes01.wav",
    "sound\\Zerg\\BUGGUY\\ZBGYes02.wav",
    "sound\\Zerg\\BUGGUY\\ZBGYes03.wav",
    "sound\\Zerg\\DEFILER\\ZDeCon00.WAV",
    "sound\\Zerg\\DEFILER\\ZDeRdy00.WAV",
    "sound\\Zerg\\DEFILER\\ZDeDth00.WAV",
    "sound\\Zerg\\DEFILER\\ZDeBlo00.WAV",
    "sound\\Zerg\\DEFILER\\ZDeBlo01.WAV",
    "sound\\Zerg\\DEFILER\\ZDePss00.WAV",
    "sound\\Zerg\\DEFILER\\ZDePss01.WAV",
    "sound\\Zerg\\DEFILER\\ZDePss02.WAV",
    "sound\\Zerg\\DEFILER\\ZDeWht00.WAV",
    "sound\\Zerg\\DEFILER\\ZDeWht01.WAV",
    "sound\\Zerg\\DEFILER\\ZDeWht02.WAV",
    "sound\\Zerg\\DEFILER\\ZDeYes00.WAV",
    "sound\\Zerg\\DEFILER\\ZDeYes01.WAV",
    "sound\\Zerg\\DEFILER\\ZDeYes02.WAV",
    "sound\\Zerg\\Egg\\ZEgRdy00.WAV",
    "sound\\Zerg\\Egg\\ZEgWht00.WAV",
    "sound\\Zerg\\Egg\\ZEgWht01.WAV",
    "sound\\Zerg\\Egg\\ZEgDth00.WAV",
    "sound\\Zerg\\Egg\\ZEgPss00.WAV",
    "sound\\Zerg\\DRONE\\ZDrRdy00.WAV",
    "sound\\Zerg\\DRONE\\ZDrDth00.WAV",
    "sound\\Zerg\\DRONE\\ZDrPss00.WAV",
    "sound\\Zerg\\DRONE\\ZDrPss01.WAV",
    "sound\\Zerg\\DRONE\\ZDrPss02.WAV",
    "sound\\Zerg\\DRONE\\ZDrWht00.WAV",
    "sound\\Zerg\\DRONE\\ZDrWht01.WAV",
    "sound\\Zerg\\DRONE\\ZDrWht02.WAV",
    "sound\\Zerg\\DRONE\\ZDrWht03.WAV",
    "sound\\Zerg\\DRONE\\ZDrWht04.WAV",
    "sound\\Zerg\\DRONE\\ZDrYes00.WAV",
    "sound\\Zerg\\DRONE\\ZDrYes01.WAV",
    "sound\\Zerg\\DRONE\\ZDrYes02.WAV",
    "sound\\Zerg\\DRONE\\ZDrYes03.WAV",
    "sound\\Zerg\\DRONE\\ZDrYes04.WAV",
    "sound\\Zerg\\DRONE\\ZDrMin00.wav",
    "sound\\Zerg\\Larva\\ZLaDth00.WAV",
    "sound\\Terran\\Advisor\\tAdErr04.WAV [5]",
    "sound\\Zerg\\Larva\\ZLaPss00.WAV",
    "sound\\Zerg\\Larva\\ZLaWht00.WAV",
    "sound\\Zerg\\Guardian\\ZGuDth00.WAV",
    "sound\\Zerg\\Guardian\\ZGuPss00.WAV",
    "sound\\Zerg\\Guardian\\ZGuPss01.WAV",
    "sound\\Zerg\\Guardian\\ZGuPss02.WAV",
    "sound\\Zerg\\Guardian\\ZGuPss03.WAV",
    "sound\\Zerg\\Guardian\\ZGuRdy00.WAV",
    "sound\\Zerg\\Guardian\\ZGuWht00.WAV",
    "sound\\Zerg\\Guardian\\ZGuWht01.WAV",
    "sound\\Zerg\\Guardian\\ZGuWht02.WAV",
    "sound\\Zerg\\Guardian\\ZGuWht03.WAV",
    "sound\\Zerg\\Guardian\\ZGuYes00.WAV",
    "sound\\Zerg\\Guardian\\ZGuYes01.WAV",
    "sound\\Zerg\\Guardian\\ZGuYes02.WAV",
    "sound\\Zerg\\Guardian\\ZGuYes03.WAV",
    "sound\\Zerg\\Hydra\\ZHyRdy00.WAV",
    "sound\\Zerg\\Hydra\\ZHyDth00.WAV",
    "sound\\Zerg\\Hydra\\ZHyPss00.WAV",
    "sound\\Zerg\\Hydra\\ZHyPss01.WAV",
    "sound\\Zerg\\Hydra\\ZHyWht00.WAV",
    "sound\\Zerg\\Hydra\\ZHyWht01.WAV",
    "sound\\Zerg\\Hydra\\ZHyWht02.WAV",
    "sound\\Zerg\\Hydra\\ZHyYes00.WAV",
    "sound\\Zerg\\Hydra\\ZHyYes01.WAV",
    "sound\\Zerg\\Hydra\\ZHyYes02.WAV",
    "sound\\Zerg\\Hydra\\ZHyYes03.WAV",
    "sound\\Zerg\\Ultra\\ZUlRor00.WAV",
    "sound\\Zerg\\Ultra\\ZUlDth00.WAV",
    "sound\\Zerg\\Ultra\\ZUlPss00.WAV",
    "sound\\Zerg\\Ultra\\ZUlPss01.WAV",
    "sound\\Zerg\\Ultra\\ZUlPss02.WAV",
    "sound\\Zerg\\Ultra\\ZUlRdy00.WAV",
    "sound\\Zerg\\Ultra\\ZUlWht00.WAV",
    "sound\\Zerg\\Ultra\\ZUlWht01.WAV",
    "sound\\Zerg\\Ultra\\ZUlWht02.WAV",
    "sound\\Zerg\\Ultra\\ZUlWht03.WAV",
    "sound\\Zerg\\Ultra\\ZUlYes00.WAV",
    "sound\\Zerg\\Ultra\\ZUlYes01.WAV",
    "sound\\Zerg\\Ultra\\ZUlYes02.WAV",
    "sound\\Zerg\\Ultra\\ZUlYes03.WAV",
    "sound\\Zerg\\Ultra\\zulAtt00.WAV",
    "sound\\Zerg\\Ultra\\zulAtt01.WAV",
    "sound\\Zerg\\Ultra\\zulAtt02.WAV",
    "sound\\Zerg\\Ultra\\zulHit00.WAV",
    "sound\\Zerg\\Ultra\\zulHit01.WAV",
    "sound\\Zerg\\Zergling\\ZZeDth00.WAV",
    "sound\\Zerg\\Zergling\\ZZePss00.WAV",
    "sound\\Zerg\\Zergling\\ZZePss01.WAV",
    "sound\\Zerg\\Zergling\\ZZePss02.WAV",
    "sound\\Zerg\\Zergling\\ZZeRdy00.WAV",
    "sound\\Zerg\\Zergling\\ZZeWht00.WAV",
    "sound\\Zerg\\Zergling\\ZZeWht01.WAV",
    "sound\\Zerg\\Zergling\\ZZeWht02.WAV",
    "sound\\Zerg\\Zergling\\ZZeWht03.WAV",
    "sound\\Zerg\\Zergling\\ZZeYes00.WAV",
    "sound\\Zerg\\Zergling\\ZZeYes01.WAV",
    "sound\\Zerg\\Zergling\\ZZeYes02.WAV",
    "sound\\Zerg\\Zergling\\ZZeYes03.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvRdy00.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvDth00.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvPss00.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvWht00.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvWht01.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvWht02.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvWht03.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvYes00.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvYes01.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvYes02.WAV",
    "sound\\Zerg\\OVERLORD\\ZOvYes03.WAV",
    "sound\\Zerg\\Queen\\ZQuTag00.WAV",
    "sound\\Zerg\\Queen\\ZQuTag01.WAV",
    "sound\\Zerg\\Queen\\ZQuSwm00.WAV",
    "sound\\Zerg\\Queen\\ZQuSwm01.WAV",
    "sound\\Zerg\\Queen\\ZQuEns00.WAV",
    "sound\\Zerg\\Queen\\ZQuDth00.WAV",
    "sound\\Zerg\\Queen\\ZQuDth01.WAV",
    "sound\\Zerg\\Queen\\ZQuDth02.WAV",
    "sound\\Zerg\\Queen\\ZQuRdy00.WAV",
    "sound\\Zerg\\Queen\\ZQuPss00.WAV",
    "sound\\Zerg\\Queen\\ZQuPss01.WAV",
    "sound\\Zerg\\Queen\\ZQuPss02.WAV",
    "sound\\Zerg\\Queen\\ZQuPss03.WAV",
    "sound\\Zerg\\Queen\\ZQuWht00.WAV",
    "sound\\Zerg\\Queen\\ZQuWht01.WAV",
    "sound\\Zerg\\Queen\\ZQuWht02.WAV",
    "sound\\Zerg\\Queen\\ZQuWht03.WAV",
    "sound\\Zerg\\Queen\\ZQuYes00.WAV",
    "sound\\Zerg\\Queen\\ZQuYes01.WAV",
    "sound\\Zerg\\Queen\\ZQuYes02.WAV",
    "sound\\Zerg\\Queen\\ZQuYes03.WAV",
    "sound\\Zerg\\Mutalid\\ZMuRdy00.WAV",
    "sound\\Zerg\\Mutalid\\ZMuDth00.WAV",
    "sound\\Zerg\\Mutalid\\ZMuPss00.WAV",
    "sound\\Zerg\\Mutalid\\ZMuPss01.WAV",
    "sound\\Zerg\\Mutalid\\ZMuPss02.WAV",
    "sound\\Zerg\\Mutalid\\ZMuPss03.WAV",
    "sound\\Zerg\\Mutalid\\ZMuWht00.WAV",
    "sound\\Zerg\\Mutalid\\ZMuWht01.WAV",
    "sound\\Zerg\\Mutalid\\ZMuWht02.WAV",
    "sound\\Zerg\\Mutalid\\ZMuWht03.WAV",
    "sound\\Zerg\\Mutalid\\ZMuYes00.WAV",
    "sound\\Zerg\\Mutalid\\ZMuYes01.WAV",
    "sound\\Zerg\\Mutalid\\ZMuYes02.WAV",
    "sound\\Zerg\\Mutalid\\ZMuYes03.WAV",
    "sound\\Zerg\\ZERGKERRI\\UKiPss00.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiPss01.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiPss02.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiPss03.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiWht00.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiWht01.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiWht02.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiWht03.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiYes00.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiYes01.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiYes02.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiYes03.wav",
    "sound\\Zerg\\ZERGKERRI\\UKiDth00.wav",
    "sound\\Misc\\CRITTERS\\PbWht01.wav",
    "sound\\Misc\\CRITTERS\\PbWht02.wav",
    "sound\\Misc\\CRITTERS\\PbWht03.wav",
    "sound\\Misc\\CRITTERS\\PBDeath01.wav",
    "sound\\Misc\\CRITTERS\\ScWht01.wav",
    "sound\\Misc\\CRITTERS\\ScWht02.wav",
    "sound\\Misc\\CRITTERS\\ScWht03.wav",
    "sound\\Misc\\CRITTERS\\ScDeath01.wav",
    "sound\\Misc\\CRITTERS\\TerWht01.wav",
    "sound\\Misc\\CRITTERS\\TerWht02.wav",
    "sound\\Misc\\CRITTERS\\TerWht03.wav",
    "sound\\Misc\\CRITTERS\\TerDeath01.wav",
    "sound\\Terran\\Duran\\TDnPss00.wav",
    "sound\\Terran\\Duran\\TDnPss01.wav",
    "sound\\Terran\\Duran\\TDnPss02.wav",
    "sound\\Terran\\Duran\\TDnPss03.wav",
    "sound\\Terran\\Duran\\TDnPss04.wav",
    "sound\\Terran\\Duran\\TDnPss05.wav",
    "sound\\Terran\\Duran\\TDnPss06.wav",
    "sound\\Terran\\Duran\\TDnPss07.wav",
    "sound\\Terran\\Duran\\TDnPss08.wav",
    "sound\\Terran\\Duran\\TDnWht00.wav",
    "sound\\Terran\\Duran\\TDnWht01.wav",
    "sound\\Terran\\Duran\\TDnWht02.wav",
    "sound\\Terran\\Duran\\TDnWht03.wav",
    "sound\\Terran\\Duran\\TDnYes00.wav",
    "sound\\Terran\\Duran\\TDnYes01.wav",
    "sound\\Terran\\Duran\\TDnYes02.wav",
    "sound\\Terran\\Duran\\TDnYes03.wav",
    "sound\\Terran\\Duran\\TDnDth00.wav",
    "sound\\Terran\\Medic\\TmedCure.wav",
    "sound\\Terran\\Medic\\TMdRdy00.wav",
    "sound\\Terran\\Medic\\TMdDth00.wav",
    "sound\\Terran\\Medic\\TMdWht00.wav",
    "sound\\Terran\\Medic\\TMdWht01.WAV",
    "sound\\Terran\\Medic\\TMdWht02.WAV",
    "sound\\Terran\\Medic\\TMdWht03.wav",
    "sound\\Terran\\Medic\\TMdYes00.wav",
    "sound\\Terran\\Medic\\TMdYes01.wav",
    "sound\\Terran\\Medic\\TMdYes02.wav",
    "sound\\Terran\\Medic\\TMdYes03.wav",
    "sound\\Terran\\Medic\\TMdPss00.wav",
    "sound\\Terran\\Medic\\TMdPss01.WAV",
    "sound\\Terran\\Medic\\TMdPss02.WAV",
    "sound\\Terran\\Medic\\TMdPss03.WAV",
    "sound\\Terran\\Medic\\TMdPss04.WAV",
    "sound\\Terran\\Medic\\TMdPss05.WAV",
    "sound\\Terran\\Medic\\TMdPss06.wav",
    "sound\\Terran\\Medic\\TMedflsh.wav",
    "sound\\Terran\\Medic\\TMedRest.wav",
    "sound\\Terran\\Medic\\TMedHeal.wav",
    "sound\\Terran\\Medic\\Miopia1.wav",
    "sound\\Terran\\Frigate\\AfterOn.wav",
    "sound\\Terran\\Frigate\\AfterOff.wav",
    "sound\\Bullet\\Tfrhit.wav",
    "sound\\Bullet\\Tfrshoot.wav",
    "sound\\Terran\\FRIGATE\\TVkRdy00.WAV",
    "sound\\Terran\\FRIGATE\\TVkPss00.WAV",
    "sound\\Terran\\FRIGATE\\TVkPss01.WAV",
    "sound\\Terran\\FRIGATE\\TVkPss02.WAV",
    "sound\\Terran\\FRIGATE\\TVkPss03.WAV",
    "sound\\Terran\\FRIGATE\\TVkPss04.WAV",
    "sound\\Terran\\FRIGATE\\TVkPss05.WAV",
    "sound\\Terran\\FRIGATE\\TVkWht00.WAV",
    "sound\\Terran\\FRIGATE\\TVkWht01.WAV",
    "sound\\Terran\\FRIGATE\\TVkWht02.WAV",
    "sound\\Terran\\FRIGATE\\TVkWht03.WAV",
    "sound\\Terran\\FRIGATE\\TVkYes00.WAV",
    "sound\\Terran\\FRIGATE\\TVkYes01.WAV",
    "sound\\Terran\\FRIGATE\\TVkYes02.WAV",
    "sound\\Terran\\FRIGATE\\TVkYes03.WAV",
    "sound\\Terran\\FRIGATE\\TVkYes04.WAV",
    "sound\\Terran\\FRIGATE\\TVkDth00.WAV",
    "sound\\Protoss\\Corsair\\PCoRdy00.wav",
    "sound\\Protoss\\Corsair\\PCorhit1.wav",
    "sound\\Protoss\\Corsair\\PCorhit2.wav",
    "sound\\Protoss\\Corsair\\PCoWht00.wav",
    "sound\\Protoss\\Corsair\\PCoWht01.WAV",
    "sound\\Protoss\\Corsair\\PCoWht02.WAV",
    "sound\\Protoss\\Corsair\\PCoWht03.wav",
    "sound\\Protoss\\Corsair\\PCoYes00.wav",
    "sound\\Protoss\\Corsair\\PCoYes01.WAV",
    "sound\\Protoss\\Corsair\\PCoYes02.WAV",
    "sound\\Protoss\\Corsair\\PCoYes03.wav",
    "sound\\Protoss\\Corsair\\PCoPss00.wav",
    "sound\\Protoss\\Corsair\\PCoPss01.WAV",
    "sound\\Protoss\\Corsair\\PCoPss02.WAV",
    "sound\\Protoss\\Corsair\\PCoPss03.WAV",
    "sound\\Protoss\\Corsair\\PCoPss04.WAV",
    "sound\\Protoss\\Corsair\\PCoPss05.WAV",
    "sound\\Protoss\\Corsair\\PCoPss06.wav",
    "sound\\Protoss\\Corsair\\PCorWeb1.wav",
    "sound\\Protoss\\Corsair\\PCorlasr2.wav",
    "sound\\Protoss\\Darchon\\feedback.wav",
    "sound\\Protoss\\Darchon\\mind.wav",
    "sound\\Protoss\\Darchon\\ParaAttk.wav",
    "sound\\Protoss\\Darchon\\Parahit.wav",
    "sound\\Protoss\\DARCHON\\PDaRdy00.WAV",
    "sound\\Protoss\\DARCHON\\PDrDth00.WAV",
    "sound\\Protoss\\DARCHON\\PDaPss00.WAV",
    "sound\\Protoss\\DARCHON\\PDaPss01.WAV",
    "sound\\Protoss\\DARCHON\\PDaPss02.WAV",
    "sound\\Protoss\\DARCHON\\PDaPss03.WAV",
    "sound\\Protoss\\DARCHON\\PDaWht00.WAV",
    "sound\\Protoss\\DARCHON\\PDaWht01.WAV",
    "sound\\Protoss\\DARCHON\\PDaWht02.WAV",
    "sound\\Protoss\\DARCHON\\PDaWht03.WAV",
    "sound\\Protoss\\DARCHON\\PDaYes00.WAV",
    "sound\\Protoss\\DARCHON\\PDaYes01.WAV",
    "sound\\Protoss\\DARCHON\\PDaYes02.WAV",
    "sound\\Protoss\\DARCHON\\PDaYes03.WAV",
    "sound\\Zerg\\LURKER\\ZLuRdy00.WAV",
    "sound\\Zerg\\LURKER\\ZLuDth00.WAV",
    "sound\\Zerg\\LURKER\\ZLuPss00.WAV",
    "sound\\Zerg\\Lurker\\ZLuPss01.WAV",
    "sound\\Zerg\\Lurker\\ZLuPss02.WAV",
    "sound\\Zerg\\LURKER\\ZLuPss03.WAV",
    "sound\\Zerg\\LURKER\\ZLuWht00.WAV",
    "sound\\Zerg\\LURKER\\ZLuWht01.WAV",
    "sound\\Zerg\\LURKER\\ZLuWht02.WAV",
    "sound\\Zerg\\LURKER\\ZLuWht03.WAV",
    "sound\\Zerg\\LURKER\\ZLuYes00.WAV",
    "sound\\Zerg\\LURKER\\ZLuYes01.WAV",
    "sound\\Zerg\\LURKER\\ZLuYes02.WAV",
    "sound\\Zerg\\LURKER\\ZLuYes03.WAV",
    "sound\\Zerg\\LURKER\\ZLuBurrw.wav",
    "sound\\Zerg\\Devourer\\firesuck.wav",
    "sound\\Zerg\\Devourer\\goophit.wav",
    "sound\\Zerg\\Devourer\\ZDvRdy00.WAV",
    "sound\\Zerg\\Devourer\\ZDvDth00.WAV",
    "sound\\Zerg\\Devourer\\ZDvPss00.WAV",
    "sound\\Zerg\\Devourer\\ZDvPss01.WAV",
    "sound\\Zerg\\Devourer\\ZDvPss02.WAV",
    "sound\\Zerg\\Devourer\\ZDvWht00.WAV",
    "sound\\Zerg\\Devourer\\ZDvWht01.WAV",
    "sound\\Zerg\\Devourer\\ZDvWht02.WAV",
    "sound\\Zerg\\Devourer\\ZDvYes00.WAV",
    "sound\\Zerg\\Devourer\\ZDvYes01.WAV",
    "sound\\Zerg\\Devourer\\ZDvYes02.WAV",
    "sound\\Zerg\\Devourer\\ZDvYes03.WAV",
    "sound\\Bullet\\ZLrkFir1.wav",
    "sound\\Bullet\\ZLrkFir2.wav",
    "sound\\Bullet\\ZLrkHit1.wav",
    "sound\\Bullet\\ZLrkHit2.wav",
    "sound\\Zerg\\ZergDuran\\ZDnPss00.wav",
    "sound\\Zerg\\ZergDuran\\ZDnPss01.wav",
    "sound\\Zerg\\ZergDuran\\ZDnPss02.wav",
    "sound\\Zerg\\ZergDuran\\ZDnPss03.wav",
    "sound\\Zerg\\ZergDuran\\ZDnPss04.wav",
    "sound\\Zerg\\ZergDuran\\ZDnPss05.wav",
    "sound\\Zerg\\ZergDuran\\ZDnPss06.wav",
    "sound\\Zerg\\ZergDuran\\ZDnPss07.wav",
    "sound\\Zerg\\ZergDuran\\ZDnPss08.wav",
    "sound\\Zerg\\ZergDuran\\ZDnWht00.wav",
    "sound\\Zerg\\ZergDuran\\ZDnWht01.wav",
    "sound\\Zerg\\ZergDuran\\ZDnWht02.wav",
    "sound\\Zerg\\ZergDuran\\ZDnWht03.wav",
    "sound\\Zerg\\ZergDuran\\ZDnYes00.wav",
    "sound\\Zerg\\ZergDuran\\ZDnYes01.wav",
    "sound\\Zerg\\ZergDuran\\ZDnYes02.wav",
    "sound\\Zerg\\ZergDuran\\ZDnYes03.wav",
    "sound\\Zerg\\ZergDuran\\ZDnDth00.wav",
    "sound\\Protoss\\Artanis\\PAtPss00.wav",
    "sound\\Protoss\\Artanis\\PAtPss01.wav",
    "sound\\Protoss\\Artanis\\PAtPss02.wav",
    "sound\\Protoss\\Artanis\\PAtPss03.wav",
    "sound\\Protoss\\Artanis\\PAtPss04.wav",
    "sound\\Protoss\\Artanis\\PAtPss05.wav",
    "sound\\Protoss\\Artanis\\PAtWht00.wav",
    "sound\\Protoss\\Artanis\\PAtWht01.wav",
    "sound\\Protoss\\Artanis\\PAtWht02.wav",
    "sound\\Protoss\\Artanis\\PAtWht03.wav",
    "sound\\Protoss\\Artanis\\PAtYes00.wav",
    "sound\\Protoss\\Artanis\\PAtYes01.wav",
    "sound\\Protoss\\Artanis\\PAtYes02.wav",
    "sound\\Protoss\\Artanis\\PAtYes03.wav"
};
