#ifndef ACTIONDESCRIPTOR_H
#define ACTIONDESCRIPTOR_H

enum class ActionDescriptor
{
    None = 0,
    // Misc
    BeginPaste,
    PasteMisc,
    DeleteSelection,
    UpdateMiscSelection,
    ChangeTileset,
    ResizeMap,
    UpdateSaveType,
    UpdateSaveSections,
    ClearSelections,
    SelectAll,
    SetPassword,
    AddSaveSection,
    RemoveSaveSection,
    UpdateMapVersion,
    ResetVcod,
    // Terrain
    BrushIsom,
    UpdateTileSel,
    ClearTileSel,
    DeleteTiles,
    PasteTiles,
    FillPasteTiles,
    OpenTileProperties,
    UpdateTileValue,
    ValidateTileOccupiers,
    // Doodads
    CreateDoodad,
    UpdateDoodadSel,
    ClearDoodadSel,
    PasteDoodad,
    DeleteDoodad,
    MoveDoodad,
    ConvertDoodad,
    UpdateDoodadPlayer,
    // Fog of War
    BrushFog,
    PasteFog,
    DeleteFogTiles,
    UpdateTileFog,
    // Locations
    UpdateLocationSel,
    ClearLocationSel,
    CreateLocation,
    ReplaceLocation,
    MoveLocation,
    DeleteLocations,
    InvertLocationXc,
    InvertLocationYc,
    InvertLocationXcYc,
    ToggleLocationLowGround,
    ToggleLocationMedGround,
    ToggleLocationHighGround,
    ToggleLocationLowAir,
    ToggleLocationMedAir,
    ToggleLocationHighAir,
    UpdateLocationName,
    UpdateLocationRawFlags,
    AdjustLocationLeft,
    AdjustLocationTop,
    AdjustLocationRight,
    AdjustLocationBottom,
    TrimLocationsToOriginal,
    // Units
    UpdateUnitSel,
    ClearUnitSel,
    CreateUnit,
    PasteUnits,
    DeleteUnits,
    StackUnits,
    CreateLocationForUnit,
    CreateInvertedLocationForUnit,
    CreateMobileInvertedLocationForUnit,
    UpdateUnitOwner,
    MoveUnits,
    ToggleUnitLinked,
    ToggleUnitInvincible,
    ToggleUnitHallucinated,
    ToggleUnitBurrowed,
    ToggleUnitCloaked,
    ToggleUnitLifted,
    UpdateUnitHp,
    UpdateUnitMp,
    UpdateUnitShields,
    UpdateUnitResources,
    UpdateUnitHangar,
    ChangeUnitType,
    AdjustUnitXc,
    AdjustUnitYc,
    AdjustUnitPosition,
    ToggleUnitValidFieldOwner,
    ToggleUnitValidFieldLife,
    ToggleUnitValidFieldMana,
    ToggleUnitValidFieldShields,
    ToggleUnitValidFieldResources,
    ToggleUnitValidFieldHangar,
    UpdateUnitValidFieldRawFlags,
    ToggleUnitValidStateInvincible,
    ToggleUnitValidStateBurrowed,
    ToggleUnitValidStateHallucinated,
    ToggleUnitValidStateCloaked,
    ToggleUnitValidStateLifted,
    UpdateUnitValidStateRawFlags,
    UpdateUnitStateRawFlags,
    UpdateUnitUnused,
    UpdateUnitUniqueId,
    UpdateUnitLinkedId,
    ToggleUnitNydusLink,
    ToggleUnitAddonLink,
    UpdateUnitRelationRawFlags,
    // Sprites
    UpdateSpriteSel,
    ClearSpriteSel,
    CreateSprite,
    PasteSprites,
    DeleteSprites,
    StackSprites,
    UpdateSpriteOwner,
    MoveSprites,
    UpdateSpriteFlags,
    ChangeSpriteType,
    UpdateSpriteUnused,
    AdjustSpriteXc,
    AdjustSpriteYc,
    AdjustSpritePosition,
    // Cut Copy Paste
    // Scenario
    SetScenarioName,
    SetScenarioDescription,
    // Players
    SetSlotPlayerType,
    SetPlayerRace,
    SetPlayerColor,
    SetPlayerForce,
    // Forces
    UpdateForceName,
    // Unit Properties
    UpdateUnitName,
    ToggleUnitTypeUsesDefaultSettings,
    UpdateUnitTypeHitpoints,
    UpdateUnitTypeShields,
    UpdateUnitTypeArmor,
    UpdateUnitTypeBuildTime,
    UpdateUnitTypeMineralCost,
    UpdateUnitTypeGasCost,
    SetUnitTypeBuildable,
    SetUnitTypeDefaultBuildable,
    SetPlayerUsesDefaultUnitBuildability,
    ResetAllUnitProperites,
    // Weapons
    UpdateWeaponBaseDamage,
    UpdateWeaponUpgradeDamage,
    // Upgrades
    SetUpgradeUsesDefaultCosts,
    SetUpgradeBaseMineralCost,
    SetUpgradeMineralCostFactor,
    SetUpgradeBaseGasCost,
    SetUpgradeGasCostFactor,
    SetUpgradeBaseResearchTime,
    SetUpgradeResearchTimeFactor,
    SetStartUpgradeLevel,
    SetMaxUpgradeLevel,
    SetDefaultStartUpgradeLevel,
    SetDefaultMaxUpgradeLevel,
    SetPlayerUsesDefaultUpgradeLeveling,
    ResetAllUpgradeProperties,
    // Techs
    SetTechUsesDefaultSettings,
    SetTechMineralCost,
    SetTechGasCost,
    SetTechResearchTime,
    SetTechEnergyCost,
    SetTechAvailable,
    SetTechResearched,
    SetTechDefaultAvailable,
    SetTechDefaultResearched,
    SetPlayerUsesDefaultTechSettings,
    ResetAllTechProperties,
    // Strings
    SetStringProperties,
    AddString,
    ReplaceString,
    DeleteString,
    MoveString,
    RescopeString,
    // Sounds
    AddSound,
    // CUWPs
    AddCuwp,
    SetCuwp,
    SetCuwpUsed,
    // Switches
    SetSwitchName,
    // Triggers
    AddTrigger,
    DeleteTrigger,
    MoveTrigger,
    ReplaceTriggerRange,
    CreateExtendedTriggerData,
    DeleteExtendedTriggerData,
    ChangeTriggerActionType,
    ChangeTriggerActionString,
    ChangeTriggerActionSound,
    SetTriggerActionUnitProperties,
    ChangeTriggerConditionType,
    UpdateTriggerRawFlags,
    UpdateTriggerComment,
    UpdateTriggerNotes,
    ToggleTriggerOwner,
    UpdateTriggerRawPlayers,
    // BriefingTriggers
    AddBriefingTrigger,
    DeleteBriefingTrigger,
    MoveBriefingTrigger,
    ReplaceBriefingTriggerRange,
    ChangeBriefingActionType,
    ChangeBriefingActionString,
    ChangeBriefingActionSound,
    ChangeBriefingTrigPlayers,
    // Plugins/Scripts
    RepairSounds,
    RepairStrings
};

struct DescriptorIndex {
    ActionDescriptor descriptorIndex = ActionDescriptor::None;
    constexpr DescriptorIndex() noexcept = default;
    constexpr DescriptorIndex(ActionDescriptor actionDescriptor) noexcept : descriptorIndex(actionDescriptor) {}
    friend constexpr bool operator==(const DescriptorIndex & lhs, const DescriptorIndex & rhs) noexcept { return lhs.descriptorIndex == rhs.descriptorIndex; }
};

#endif